/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * life 模块的面板与弹窗标记。
 *
 * 事实源：design/life/life_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <LifeWorkspace />（同目录）。
 */

import { ToggleRow, TaskCheck, TaskText } from '../../../components/workspace/toggles'

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'overview', label: '概览' },
  { key: 'habits', label: '习惯' },
  { key: 'tasks', label: '任务' },
  { key: 'calendar', label: '日程' },
  { key: 'finance', label: '财务' },
  { key: 'health', label: '健康' },
  { key: 'fitness', label: '运动' },
  { key: 'recipes', label: '食谱' },
  { key: 'pets', label: '宠物' },
  { key: 'journal', label: '日记' },
  { key: 'goals', label: '目标' },
]

/** 本模块所有交互回调 —— 实现写在 <LifeWorkspace /> 里。 */
export interface Handlers {
  closeModal: () => void
  notice: (arg0: string) => void
  openPet: (arg0: string) => void
  openRecipe: (arg0: string) => void
  openWorkoutForm: () => void
}

export const MODAL_SPECS = {
  openWorkoutForm: { title: '记录运动' },
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function OverviewPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>下午好，杨刘 👋</h1>
      <p>今天是 2026-09-20 星期日，关注平衡与节奏。</p>
      <div className="hero-meta">
      <span>习惯：<strong>3 / 5</strong></span>
      <span>任务：<strong>2 / 6</strong></span>
      <span>运动：<strong>32 分钟</strong></span>
      <span>支出：<strong>¥3,240</strong></span>
      <span>猫猫：<strong>团子</strong></span>
      </div>
      </section>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">习惯打卡</div>
      <div className="stat">3 / 5</div>
      <div className="stat-desc">今日已完成 3 项</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "60%" }}></div></div>
      </div>
      <div className="card">
      <div className="card-title">今日运动</div>
      <div className="stat">32 分钟</div>
      <div className="stat-desc">跑步 · 4.2 km</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "64%" }}></div></div>
      </div>
      <div className="card">
      <div className="card-title">猫猫提醒</div>
      <div className="stat">2</div>
      <div className="stat-desc">驱虫 3 天后 · 猫粮快没了</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "80%" }}></div></div>
      </div>
      </section>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">今日任务</div>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>买菜</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>铲屎</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>整理房间</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>买猫粮</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>给爸妈打电话</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      </div>
      <div className="card">
      <div className="card-title">最近日记</div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-20 <span className="journal-mood">😊</span></div>
      <div className="journal-text">团子今天很粘人，趴键盘上不让我工作。</div>
      </div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-19 <span className="journal-mood">😌</span></div>
      <div className="journal-text">晚上散步半小时，很放松。</div>
      </div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-18 <span className="journal-mood">😐</span></div>
      <div className="journal-text">有点累，早点休息。</div>
      </div>
      </div>
      </section>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">今日食谱</div>
      <div className="recipe-card" onClick={() => handlers.openRecipe('番茄牛腩')}>
      <div className="recipe-name">番茄牛腩</div>
      <div className="recipe-meta">晚餐 · 中等 · 60 分钟</div>
      <div className="recipe-tags">
      <span className="recipe-tag">高蛋白</span>
      <span className="recipe-tag">家常</span>
      </div>
      </div>
      <div className="recipe-card" onClick={() => handlers.openRecipe('燕麦牛奶')}>
      <div className="recipe-name">燕麦牛奶</div>
      <div className="recipe-meta">早餐 · 简单 · 5 分钟</div>
      <div className="recipe-tags">
      <span className="recipe-tag">快手</span>
      <span className="recipe-tag">低卡</span>
      </div>
      </div>
      </div>
      <div className="card">
      <div className="card-title">健康摘要</div>
      <div className="health-row"><span>睡眠</span><span className="health-value">7h 20m</span></div>
      <div className="health-row"><span>运动</span><span className="health-value">32 分钟</span></div>
      <div className="health-row"><span>体重</span><span className="health-value">68.5 kg</span></div>
      <div className="health-row"><span>步数</span><span className="health-value">8,420 步</span></div>
      </div>
      </section>
    </>
  )
}

export function HabitsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">习惯打卡 · 本周</div>
      <div className="habit-item">
      <div className="habit-name">早起 7:00</div>
      <div className="habit-days">
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div><div className="habit-day"></div>
      <div className="habit-day"></div>
      </div>
      </div>
      <div className="habit-item">
      <div className="habit-name">运动 30 分钟</div>
      <div className="habit-days">
      <div className="habit-day done"></div><div className="habit-day"></div>
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day"></div><div className="habit-day done"></div>
      <div className="habit-day"></div>
      </div>
      </div>
      <div className="habit-item">
      <div className="habit-name">阅读 20 页</div>
      <div className="habit-days">
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day"></div>
      </div>
      </div>
      <div className="habit-item">
      <div className="habit-name">铲屎</div>
      <div className="habit-days">
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div><div className="habit-day done"></div>
      <div className="habit-day done"></div>
      </div>
      </div>
      <div className="habit-item">
      <div className="habit-name">冥想 10 分钟</div>
      <div className="habit-days">
      <div className="habit-day"></div><div className="habit-day done"></div>
      <div className="habit-day"></div><div className="habit-day done"></div>
      <div className="habit-day"></div><div className="habit-day"></div>
      <div className="habit-day"></div>
      </div>
      </div>
      </section>
    </>
  )
}

export function TasksPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">生活任务</div>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>买菜</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>铲屎</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>整理房间</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>买猫粮</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>给爸妈打电话</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>预约体检</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      </section>
    </>
  )
}

export function CalendarPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">2026 年 9 月</div>
      <div className="calendar-grid">
      <div className="cal-head">一</div><div className="cal-head">二</div>
      <div className="cal-head">三</div><div className="cal-head">四</div>
      <div className="cal-head">五</div><div className="cal-head">六</div>
      <div className="cal-head">日</div>
      <div className="cal-day muted">31</div>
      <div className="cal-day">1</div>
      <div className="cal-day">2</div>
      <div className="cal-day has-event">3</div>
      <div className="cal-day">4</div>
      <div className="cal-day has-event">5</div>
      <div className="cal-day">6</div>
      <div className="cal-day">7</div>
      <div className="cal-day">8</div>
      <div className="cal-day has-event">9</div>
      <div className="cal-day">10</div>
      <div className="cal-day">11</div>
      <div className="cal-day has-event">12</div>
      <div className="cal-day">13</div>
      <div className="cal-day">14</div>
      <div className="cal-day">15</div>
      <div className="cal-day">16</div>
      <div className="cal-day">17</div>
      <div className="cal-day">18</div>
      <div className="cal-day has-event">19</div>
      <div className="cal-day today has-event">20</div>
      <div className="cal-day">21</div>
      <div className="cal-day">22</div>
      <div className="cal-day has-event">23</div>
      <div className="cal-day">24</div>
      <div className="cal-day">25</div>
      <div className="cal-day">26</div>
      <div className="cal-day">27</div>
      <div className="cal-day">28</div>
      <div className="cal-day">29</div>
      <div className="cal-day">30</div>
      <div className="cal-day muted">1</div>
      <div className="cal-day muted">2</div>
      <div className="cal-day muted">3</div>
      <div className="cal-day muted">4</div>
      </div>
      </section>
    </>
  )
}

export function FinancePanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">本月收入</div>
      <div className="stat" style={{ color: "#10B981" }}>¥12,000</div>
      <div className="stat-desc">工资 + 副业</div>
      </div>
      <div className="card">
      <div className="card-title">本月支出</div>
      <div className="stat" style={{ color: "#EF4444" }}>¥3,240</div>
      <div className="stat-desc">预算 ¥5,000</div>
      </div>
      <div className="card">
      <div className="card-title">本月结余</div>
      <div className="stat">¥8,760</div>
      <div className="stat-desc">结余率 73%</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">最近支出</div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🍜</div><div>午餐</div></div>
      <div className="finance-amount expense">- ¥38</div>
      </div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🐱</div><div>猫粮</div></div>
      <div className="finance-amount expense">- ¥189</div>
      </div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🥬</div><div>食材</div></div>
      <div className="finance-amount expense">- ¥76</div>
      </div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">💰</div><div>副业收入</div></div>
      <div className="finance-amount income">+ ¥500</div>
      </div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🏃</div><div>运动装备</div></div>
      <div className="finance-amount expense">- ¥299</div>
      </div>
      </section>
    </>
  )
}

export function HealthPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">今日数据</div>
      <div className="health-row"><span>睡眠</span><span className="health-value">7h 20m</span></div>
      <div className="health-row"><span>运动</span><span className="health-value">32 分钟</span></div>
      <div className="health-row"><span>步数</span><span className="health-value">8,420 步</span></div>
      <div className="health-row"><span>体重</span><span className="health-value">68.5 kg</span></div>
      <div className="health-row"><span>喝水</span><span className="health-value">1.2 L</span></div>
      </div>
      <div className="card">
      <div className="card-title">本周趋势</div>
      <div className="health-row"><span>平均睡眠</span><span className="health-value">7h 05m</span></div>
      <div className="health-row"><span>运动次数</span><span className="health-value">4 次</span></div>
      <div className="health-row"><span>平均步数</span><span className="health-value">7,860 步</span></div>
      <div className="health-row"><span>体重变化</span><span className="health-value">-0.3 kg</span></div>
      </div>
      </section>
    </>
  )
}

export function FitnessPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">本周运动</div>
      <div className="stat">4 次</div>
      <div className="stat-desc">共 142 分钟</div>
      </div>
      <div className="card">
      <div className="card-title">本周消耗</div>
      <div className="stat">1,280</div>
      <div className="stat-desc">千卡</div>
      </div>
      <div className="card">
      <div className="card-title">本周距离</div>
      <div className="stat">16.8 km</div>
      <div className="stat-desc">跑步 + 骑行</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
      <span>最近运动</span>
      <button className="btn btn-primary" onClick={() => handlers.openWorkoutForm()}>+ 记录运动</button>
      </div>
      <div className="workout-item">
      <div className="workout-icon">🏃</div>
      <div className="workout-info">
      <div className="workout-name">跑步</div>
      <div className="workout-meta">2026-09-20 · 32 分钟 · 4.2 km</div>
      </div>
      <div className="workout-value">320 kcal</div>
      </div>
      <div className="workout-item">
      <div className="workout-icon">🚴</div>
      <div className="workout-info">
      <div className="workout-name">骑行</div>
      <div className="workout-meta">2026-09-19 · 45 分钟 · 12.6 km</div>
      </div>
      <div className="workout-value">480 kcal</div>
      </div>
      <div className="workout-item">
      <div className="workout-icon">🧘</div>
      <div className="workout-info">
      <div className="workout-name">瑜伽</div>
      <div className="workout-meta">2026-09-18 · 30 分钟</div>
      </div>
      <div className="workout-value">120 kcal</div>
      </div>
      <div className="workout-item">
      <div className="workout-icon">💪</div>
      <div className="workout-info">
      <div className="workout-name">力量训练</div>
      <div className="workout-meta">2026-09-17 · 35 分钟</div>
      </div>
      <div className="workout-value">360 kcal</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">本周计划</div>
      <div className="workout-item">
      <div className="workout-icon">🏃</div>
      <div className="workout-info"><div className="workout-name">跑步 3 次</div></div>
      <div className="workout-value">2 / 3</div>
      </div>
      <div className="workout-item">
      <div className="workout-icon">💪</div>
      <div className="workout-info"><div className="workout-name">力量 2 次</div></div>
      <div className="workout-value">1 / 2</div>
      </div>
      <div className="workout-item">
      <div className="workout-icon">🧘</div>
      <div className="workout-info"><div className="workout-name">瑜伽 2 次</div></div>
      <div className="workout-value">1 / 2</div>
      </div>
      </section>
    </>
  )
}

export function RecipesPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">收藏食谱</div>
      <div className="stat">24</div>
      <div className="stat-desc">常做 8 个</div>
      </div>
      <div className="card">
      <div className="card-title">本周菜单</div>
      <div className="stat">5 天</div>
      <div className="stat-desc">已计划 5 天</div>
      </div>
      <div className="card">
      <div className="card-title">购物清单</div>
      <div className="stat">8 项</div>
      <div className="stat-desc">待购买</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">我的食谱</div>
      <div className="recipe-card" onClick={() => handlers.openRecipe('番茄牛腩')}>
      <div className="recipe-name">番茄牛腩</div>
      <div className="recipe-meta">晚餐 · 中等 · 60 分钟 · 2 人份</div>
      <div className="recipe-tags">
      <span className="recipe-tag">高蛋白</span>
      <span className="recipe-tag">家常</span>
      <span className="recipe-tag">炖菜</span>
      </div>
      </div>
      <div className="recipe-card" onClick={() => handlers.openRecipe('燕麦牛奶')}>
      <div className="recipe-name">燕麦牛奶</div>
      <div className="recipe-meta">早餐 · 简单 · 5 分钟 · 1 人份</div>
      <div className="recipe-tags">
      <span className="recipe-tag">快手</span>
      <span className="recipe-tag">低卡</span>
      </div>
      </div>
      <div className="recipe-card" onClick={() => handlers.openRecipe('蒜蓉西兰花')}>
      <div className="recipe-name">蒜蓉西兰花</div>
      <div className="recipe-meta">午餐 · 简单 · 15 分钟 · 1 人份</div>
      <div className="recipe-tags">
      <span className="recipe-tag">素食</span>
      <span className="recipe-tag">低卡</span>
      </div>
      </div>
      <div className="recipe-card" onClick={() => handlers.openRecipe('鸡胸肉沙拉')}>
      <div className="recipe-name">鸡胸肉沙拉</div>
      <div className="recipe-meta">午餐 · 简单 · 20 分钟 · 1 人份</div>
      <div className="recipe-tags">
      <span className="recipe-tag">高蛋白</span>
      <span className="recipe-tag">减脂</span>
      </div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">购物清单</div>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>牛腩 500g</TaskText>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>番茄 4 个</TaskText>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>燕麦</TaskText>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>西兰花 2 颗</TaskText>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>鸡胸肉 2 块</TaskText>
      </ToggleRow>
      </section>
    </>
  )
}

export function PetsPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">我的宠物</div>
      <div className="pet-card" onClick={() => handlers.openPet('团子')}>
      <div className="pet-avatar">🐱</div>
      <div className="pet-info">
      <div className="pet-name">团子</div>
      <div className="pet-meta">英短 · 2 岁 3 个月 · 公 · 已绝育</div>
      <div className="pet-tags">
      <span className="pet-tag">疫苗 3 天后</span>
      <span className="pet-tag">驱虫 3 天后</span>
      <span className="pet-tag">体重 4.8kg</span>
      </div>
      </div>
      </div>
      <div className="pet-card" onClick={() => handlers.openPet('豆豆')}>
      <div className="pet-avatar">🐱</div>
      <div className="pet-info">
      <div className="pet-name">豆豆</div>
      <div className="pet-meta">布偶 · 1 岁 6 个月 · 母 · 未绝育</div>
      <div className="pet-tags">
      <span className="pet-tag">疫苗 已完成</span>
      <span className="pet-tag">体重 3.6kg</span>
      </div>
      </div>
      </div>
      </section>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">健康记录</div>
      <div className="health-row"><span>团子 · 体重</span><span className="health-value">4.8 kg</span></div>
      <div className="health-row"><span>团子 · 疫苗</span><span className="health-value">2026-09-23</span></div>
      <div className="health-row"><span>团子 · 驱虫</span><span className="health-value">2026-09-23</span></div>
      <div className="health-row"><span>豆豆 · 体重</span><span className="health-value">3.6 kg</span></div>
      <div className="health-row"><span>豆豆 · 疫苗</span><span className="health-value">已完成</span></div>
      </div>
      <div className="card">
      <div className="card-title">提醒</div>
      <div className="health-row"><span>团子 · 疫苗</span><span className="health-value">3 天后</span></div>
      <div className="health-row"><span>团子 · 驱虫</span><span className="health-value">3 天后</span></div>
      <div className="health-row"><span>猫粮</span><span className="health-value">快没了</span></div>
      <div className="health-row"><span>猫砂</span><span className="health-value">还剩 1 袋</span></div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">宠物支出</div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🐱</div><div>猫粮</div></div>
      <div className="finance-amount expense">- ¥189</div>
      </div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🐱</div><div>猫砂</div></div>
      <div className="finance-amount expense">- ¥56</div>
      </div>
      <div className="finance-row">
      <div className="finance-cat"><div className="finance-icon">🐱</div><div>疫苗</div></div>
      <div className="finance-amount expense">- ¥320</div>
      </div>
      </section>
    </>
  )
}

export function JournalPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">最近日记</div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-20 <span className="journal-mood">😊</span></div>
      <div className="journal-text">团子今天很粘人，趴键盘上不让我工作。晚上做了番茄牛腩，成功。</div>
      </div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-19 <span className="journal-mood">😌</span></div>
      <div className="journal-text">晚上散步半小时，很放松。</div>
      </div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-18 <span className="journal-mood">😐</span></div>
      <div className="journal-text">有点累，工作上的事有点多，早点休息。</div>
      </div>
      <div className="journal-entry">
      <div className="journal-date">2026-09-17 <span className="journal-mood">😊</span></div>
      <div className="journal-text">和朋友吃了顿饭，聊得很开心。</div>
      </div>
      </section>
    </>
  )
}

export function GoalsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">2026 年度目标</div>
      <div className="habit-item">
      <div className="habit-name">读 30 本书</div>
      <div style={{ fontSize: "13px", color: "var(--mw-text-secondary)" }}>18 / 30</div>
      </div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "60%" }}></div></div>
      <div className="habit-item" style={{ marginTop: "16px" }}>
      <div className="habit-name">减重 5 kg</div>
      <div style={{ fontSize: "13px", color: "var(--mw-text-secondary)" }}>2.5 / 5</div>
      </div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "50%" }}></div></div>
      <div className="habit-item" style={{ marginTop: "16px" }}>
      <div className="habit-name">存款 5 万</div>
      <div style={{ fontSize: "13px", color: "var(--mw-text-secondary)" }}>3.2 / 5</div>
      </div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "64%" }}></div></div>
      <div className="habit-item" style={{ marginTop: "16px" }}>
      <div className="habit-name">每周运动 3 次</div>
      <div style={{ fontSize: "13px", color: "var(--mw-text-secondary)" }}>4 / 3 本周</div>
      </div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "100%" }}></div></div>
      <div className="habit-item" style={{ marginTop: "16px" }}>
      <div className="habit-name">学会 10 道菜</div>
      <div style={{ fontSize: "13px", color: "var(--mw-text-secondary)" }}>6 / 10</div>
      </div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "60%" }}></div></div>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <button className="btn btn-ghost" id="quickAdd" onClick={() => handlers.notice('原型演示：快速记录')}>+ 快速记录</button>
    </>
  )
}

/** 弹窗体：原型 `openWorkoutForm` 标题「记录运动」 */
export function OpenWorkoutFormModal({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <div className="form-field">
      <label className="form-label">运动类型</label>
      <select className="form-select">
      <option>跑步</option>
      <option>骑行</option>
      <option>游泳</option>
      <option>力量训练</option>
      <option>瑜伽</option>
      <option>球类</option>
      <option>其他</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">日期</label>
      <input className="form-input" type="date" defaultValue="2026-09-20" />
      </div>
      <div className="form-field">
      <label className="form-label">时长（分钟）</label>
      <input className="form-input" type="number" placeholder="30" />
      </div>
      <div className="form-field">
      <label className="form-label">距离（km，可选）</label>
      <input className="form-input" type="number" placeholder="4.2" step="0.1" />
      </div>
      <div className="form-field">
      <label className="form-label">强度</label>
      <select className="form-select" defaultValue="中">
      <option>低</option>
      <option>中</option>
      <option>高</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">消耗（千卡，可选）</label>
      <input className="form-input" type="number" placeholder="320" />
      </div>
      <div className="form-field">
      <label className="form-label">备注</label>
      <textarea className="form-textarea" placeholder="今天状态不错..."></textarea>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>取消</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：已保存'); handlers.closeModal() }}>保存</button>
      </div>
    </>
  )
}
