/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * learning 模块的面板与弹窗标记。
 *
 * 事实源：design/study/study_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <LearningWorkspace />（同目录）。
 */

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'dashboard', label: '概览' },
  { key: 'goals', label: '学习目标' },
  { key: 'skills', label: '技能地图' },
  { key: 'resources', label: '资源库' },
  { key: 'notes', label: '笔记' },
  { key: 'review', label: '复习' },
  { key: 'practice', label: '实践项目' },
  { key: 'output', label: '输出' },
]

/** 本模块所有交互回调 —— 实现写在 <LearningWorkspace /> 里。 */
export interface Handlers {
  closeModal: () => void
  notice: (arg0: string) => void
  openNote: (arg0: string) => void
  openOutput: (arg0: string) => void
  openPractice: (arg0: string) => void
  openResource: (arg0: string) => void
  openReview: (arg0: string) => void
}

export const MODAL_SPECS = {
  openResource: { title: null, arg: true },
  openNote: { title: null, arg: true },
  openReview: { title: '复习', arg: true },
  openPractice: { title: null, arg: true },
  openOutput: { title: null, arg: true },
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function DashboardPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>学习概览 📚</h1>
      <p>今天 2026-09-20，本周已学习 8.5 小时。</p>
      <div className="hero-meta">
      <span>本周学习：<strong>8.5h</strong></span>
      <span>待复习：<strong>12</strong></span>
      <span>进行中资源：<strong>4</strong></span>
      <span>实践项目：<strong>2</strong></span>
      </div>
      </section>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">本周学习</div>
      <div className="stat">8.5h</div>
      <div className="stat-desc">目标 10h · 85%</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}><div className="progress-fill" style={{ width: "85%" }}></div></div>
      </div>
      <div className="card">
      <div className="card-title">待复习</div>
      <div className="stat">12</div>
      <div className="stat-desc">今日到期 5 条</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}><div className="progress-fill" style={{ width: "40%" }}></div></div>
      </div>
      <div className="card">
      <div className="card-title">笔记</div>
      <div className="stat">86</div>
      <div className="stat-desc">本周新增 6 条</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}><div className="progress-fill" style={{ width: "60%" }}></div></div>
      </div>
      </section>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">进行中资源</div>
      <div className="resource-item">
      <div className="resource-title">React 19 官方文档</div>
      <div className="resource-meta">文档 · 进度 45%</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "45%" }}></div></div>
      </div>
      <div className="resource-item">
      <div className="resource-title">深入理解计算机系统</div>
      <div className="resource-meta">书 · 进度 30%</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "30%" }}></div></div>
      </div>
      <div className="resource-item">
      <div className="resource-title">Vite 构建原理课程</div>
      <div className="resource-meta">课程 · 进度 60%</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "60%" }}></div></div>
      </div>
      </div>
      <div className="card">
      <div className="card-title">今日待复习</div>
      <div className="review-item" onClick={() => handlers.openReview('React 19 中 ref 的变化')}>
      <div className="review-question">React 19 中 ref 的变化？</div>
      <div className="review-meta">
      <span className="review-badge">React</span>
      <span>今日到期</span>
      </div>
      </div>
      <div className="review-item" onClick={() => handlers.openReview('Vite 预构建作用')}>
      <div className="review-question">Vite 预构建的作用？</div>
      <div className="review-meta">
      <span className="review-badge">Vite</span>
      <span>今日到期</span>
      </div>
      </div>
      <div className="review-item" onClick={() => handlers.openReview('CSS 变量切换主题')}>
      <div className="review-question">CSS 变量如何做主题切换？</div>
      <div className="review-meta">
      <span className="review-badge">CSS</span>
      <span>今日到期</span>
      </div>
      </div>
      </div>
      </section>
    </>
  )
}

export function GoalsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">2026 Q3 学习目标</div>
      <div className="goal-item">
      <div className="goal-title">掌握 React 19 + Vite 工程化</div>
      <div className="goal-desc">目标：能独立搭建并优化 React 19 项目</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "65%" }}></div></div>
      <div className="progress-label"><span>65%</span><span>截止 09-30</span></div>
      </div>
      <div className="goal-item">
      <div className="goal-title">读完 3 本技术书</div>
      <div className="goal-desc">目标：CSAPP、重构、设计模式</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "33%" }}></div></div>
      <div className="progress-label"><span>1 / 3</span><span>截止 12-31</span></div>
      </div>
      <div className="goal-item">
      <div className="goal-title">完成个人系统</div>
      <div className="goal-desc">目标：9 模块 + 双模式 + AI 能力</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "55%" }}></div></div>
      <div className="progress-label"><span>55%</span><span>截止 12-31</span></div>
      </div>
      </section>
    </>
  )
}

export function SkillsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">技能地图</div>
      <div className="skill-item">
      <div className="skill-name">React</div>
      <div className="skill-level">
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot"></div>
      </div>
      </div>
      <div className="skill-item">
      <div className="skill-name">TypeScript</div>
      <div className="skill-level">
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot"></div>
      <div className="skill-dot"></div>
      </div>
      </div>
      <div className="skill-item">
      <div className="skill-name">Vite</div>
      <div className="skill-level">
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot"></div>
      <div className="skill-dot"></div>
      </div>
      </div>
      <div className="skill-item">
      <div className="skill-name">CSS / 设计</div>
      <div className="skill-level">
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot"></div>
      </div>
      </div>
      <div className="skill-item">
      <div className="skill-name">Node.js</div>
      <div className="skill-level">
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot"></div>
      <div className="skill-dot"></div>
      </div>
      </div>
      <div className="skill-item">
      <div className="skill-name">架构设计</div>
      <div className="skill-level">
      <div className="skill-dot on"></div>
      <div className="skill-dot on"></div>
      <div className="skill-dot"></div>
      <div className="skill-dot"></div>
      <div className="skill-dot"></div>
      </div>
      </div>
      </section>
    </>
  )
}

export function ResourcesPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">进行中</div>
      <div className="resource-item" onClick={() => handlers.openResource('React 19 官方文档')}>
      <div className="resource-title">React 19 官方文档</div>
      <div className="resource-meta">文档 · 进度 45% · 最近更新 昨天</div>
      <div className="resource-tags">
      <span className="resource-tag">React</span>
      <span className="resource-tag">前端</span>
      </div>
      </div>
      <div className="resource-item" onClick={() => handlers.openResource('深入理解计算机系统')}>
      <div className="resource-title">深入理解计算机系统</div>
      <div className="resource-meta">书 · 进度 30% · 最近更新 3 天前</div>
      <div className="resource-tags">
      <span className="resource-tag">CSAPP</span>
      <span className="resource-tag">基础</span>
      </div>
      </div>
      <div className="resource-item" onClick={() => handlers.openResource('Vite 构建原理课程')}>
      <div className="resource-title">Vite 构建原理课程</div>
      <div className="resource-meta">课程 · 进度 60% · 最近更新 2 天前</div>
      <div className="resource-tags">
      <span className="resource-tag">Vite</span>
      <span className="resource-tag">构建</span>
      </div>
      </div>
      <div className="resource-item" onClick={() => handlers.openResource('弥散风格设计指南')}>
      <div className="resource-title">弥散风格设计指南</div>
      <div className="resource-meta">文章 · 进度 100% · 已完成</div>
      <div className="resource-tags">
      <span className="resource-tag">UI</span>
      <span className="resource-tag">设计</span>
      </div>
      </div>
      </section>
    </>
  )
}

export function NotesPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">最近笔记</div>
      <div className="doc-item" onClick={() => handlers.openNote('React 19 新特性')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">React 19 新特性</div>
      <div className="doc-meta">React / 前端 · 昨天</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openNote('Vite 构建优化记录')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">Vite 构建优化记录</div>
      <div className="doc-meta">Vite / 构建 · 2 天前</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openNote('弥散风格 UI 要点')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">弥散风格 UI 要点</div>
      <div className="doc-meta">UI / 设计 · 3 天前</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openNote('TypeScript 类型体操笔记')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">TypeScript 类型体操笔记</div>
      <div className="doc-meta">TS / 类型 · 5 天前</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function ReviewPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">今日待复习</div>
      <div className="review-item" onClick={() => handlers.openReview('React 19 中 ref 的变化')}>
      <div className="review-question">React 19 中 ref 的变化？</div>
      <div className="review-meta">
      <span className="review-badge">React</span>
      <span>今日到期</span>
      <span>间隔 3 天</span>
      </div>
      </div>
      <div className="review-item" onClick={() => handlers.openReview('Vite 预构建作用')}>
      <div className="review-question">Vite 预构建的作用？</div>
      <div className="review-meta">
      <span className="review-badge">Vite</span>
      <span>今日到期</span>
      <span>间隔 7 天</span>
      </div>
      </div>
      <div className="review-item" onClick={() => handlers.openReview('CSS 变量切换主题')}>
      <div className="review-question">CSS 变量如何做主题切换？</div>
      <div className="review-meta">
      <span className="review-badge">CSS</span>
      <span>今日到期</span>
      <span>间隔 3 天</span>
      </div>
      </div>
      <div className="review-item" onClick={() => handlers.openReview('TypeScript 泛型约束')}>
      <div className="review-question">TypeScript 泛型约束怎么写？</div>
      <div className="review-meta">
      <span className="review-badge">TS</span>
      <span>今日到期</span>
      <span>间隔 14 天</span>
      </div>
      </div>
      </section>
    </>
  )
}

export function PracticePanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">实践项目</div>
      <div className="doc-item" onClick={() => handlers.openPractice('个人系统前端')}>
      <div className="doc-icon">🧩</div>
      <div className="doc-info">
      <div className="doc-name">个人系统前端</div>
      <div className="doc-meta">进度 55% · 关联笔记 12 · 进行中</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openPractice('Vite 插件练习')}>
      <div className="doc-icon">🧩</div>
      <div className="doc-info">
      <div className="doc-name">Vite 插件练习</div>
      <div className="doc-meta">进度 30% · 关联笔记 5 · 进行中</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openPractice('CSS 弥散风格组件库')}>
      <div className="doc-icon">🧩</div>
      <div className="doc-info">
      <div className="doc-name">CSS 弥散风格组件库</div>
      <div className="doc-meta">进度 80% · 关联笔记 8 · 进行中</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function OutputPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">输出</div>
      <div className="doc-item" onClick={() => handlers.openOutput('弥散风格 UI 设计总结')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">弥散风格 UI 设计总结</div>
      <div className="doc-meta">博客 · 已发布 · 2026-09-15</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openOutput('Vite 构建优化实践')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">Vite 构建优化实践</div>
      <div className="doc-meta">博客 · 草稿 · 更新于 2 天前</div>
      </div>
      </div>
      <div className="doc-item" onClick={() => handlers.openOutput('React 19 学习路线')}>
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">React 19 学习路线</div>
      <div className="doc-meta">分享 · 已发布 · 2026-09-10</div>
      </div>
      </div>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <button className="btn btn-ghost" id="quickAdd" onClick={() => handlers.notice('原型演示：新建笔记')}>+ 新建笔记</button>
    </>
  )
}

/** 弹窗体：原型 `openResource` 标题由触发参数决定 */
export function OpenResourceModal({ handlers, title: _title }: { handlers: Handlers; title: string }) {
  return (
    <>
      <div className="detail-section">
      <div className="detail-label">资源信息</div>
      <ul className="detail-list">
      <li>类型：文档 / 书 / 课程 / 文章</li>
      <li>进度：45%</li>
      <li>最近更新：昨天</li>
      <li>关联技能：React / 前端</li>
      </ul>
      </div>
      <div className="detail-section">
      <div className="detail-label">关联笔记</div>
      <ul className="detail-list">
      <li>React 19 新特性</li>
      <li>Vite 构建优化记录</li>
      </ul>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-primary" onClick={() => handlers.notice('原型演示：继续学习')}>继续学习</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `openNote` 标题由触发参数决定 */
export function OpenNoteModal({ handlers, title: _title }: { handlers: Handlers; title: string }) {
  return (
    <>
      <div className="detail-section">
      <div className="detail-label">笔记内容</div>
      <div className="detail-text">这里是笔记正文，支持 Markdown、代码块、双链。</div>
      </div>
      <div className="detail-section">
      <div className="detail-label">关联</div>
      <ul className="detail-list">
      <li>资源：React 19 官方文档</li>
      <li>项目：个人系统前端</li>
      <li>标签：React / 前端</li>
      </ul>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-primary" onClick={() => handlers.notice('原型演示：升级为知识库')}>升级为知识库</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `openReview` 标题「复习」 */
export function OpenReviewModal({ handlers, question }: { handlers: Handlers; question: string }) {
  return (
    <>
      <div className="detail-section">
      <div className="detail-label">问题</div>
      <div className="detail-text">{question}</div>
      </div>
      <div className="detail-section">
      <div className="detail-label">答案</div>
      <div className="detail-text">点击「显示答案」查看。</div>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-ghost" onClick={() => handlers.notice('原型演示：显示答案')}>显示答案</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：记住了'); handlers.closeModal() }}>记住了</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `openPractice` 标题由触发参数决定 */
export function OpenPracticeModal({ handlers, title: _title }: { handlers: Handlers; title: string }) {
  return (
    <>
      <div className="detail-section">
      <div className="detail-label">项目信息</div>
      <ul className="detail-list">
      <li>进度：55%</li>
      <li>关联笔记：12 条</li>
      <li>状态：进行中</li>
      </ul>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-primary" onClick={() => handlers.notice('原型演示：进入项目')}>进入项目</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `openOutput` 标题由触发参数决定 */
export function OpenOutputModal({ handlers, title: _title }: { handlers: Handlers; title: string }) {
  return (
    <>
      <div className="detail-section">
      <div className="detail-label">输出信息</div>
      <ul className="detail-list">
      <li>类型：博客 / 分享</li>
      <li>状态：已发布 / 草稿</li>
      <li>发布时间：2026-09-15</li>
      </ul>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-primary" onClick={() => handlers.notice('原型演示：查看输出')}>查看</button>
      </div>
    </>
  )
}
