/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * tasks 模块的面板与弹窗标记。
 *
 * 事实源：design/task/task_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <TasksWorkspace />（同目录）。
 */

import { ToggleRow, TaskCheck, TaskText, DoneText } from '../../../components/workspace/toggles'

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'all', label: '全部任务' },
  { key: 'today', label: '今日' },
  { key: 'inbox', label: '收件箱' },
  { key: 'board', label: '看板' },
  { key: 'matrix', label: '四象限' },
  { key: 'calendar', label: '日历' },
  { key: 'done', label: '已完成' },
]

/** 本模块所有交互回调 —— 实现写在 <TasksWorkspace /> 里。 */
export interface Handlers {
  aiAddOpen: () => void
  closeModal: () => void
  newTaskBtnOpen: () => void
  notice: (arg0: string) => void
}

export const MODAL_SPECS = {
  newTaskBtn: { title: '新建任务' },
  aiAdd: { title: '✨ AI 拆解任务' },
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function AllPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>任务清单 ✅</h1>
      <p>跨领域任务中心，聚合生活、工作、学习。</p>
      <div className="hero-meta">
      <span>今日：<strong>3 / 8</strong></span>
      <span>进行中：<strong>5</strong></span>
      <span>逾期：<strong>2</strong></span>
      <span>本周完成：<strong>18</strong></span>
      </div>
      </section>
      <section className="card">
      <div className="quick-add">
      <input className="quick-input" placeholder="快速添加任务，回车创建..." id="quickTaskInput" onClick={() => handlers.notice('原型演示：快速添加任务，回车创建...')} />
      <button className="btn btn-primary" onClick={() => handlers.notice('原型演示：添加任务')}>添加</button>
      </div>
      </section>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">按领域</div>
      <div className="stat">24</div>
      <div className="stat-desc">生活 8 · 工作 12 · 学习 4</div>
      </div>
      <div className="card">
      <div className="card-title">按优先级</div>
      <div className="stat">24</div>
      <div className="stat-desc">高 5 · 中 12 · 低 7</div>
      </div>
      <div className="card">
      <div className="card-title">按状态</div>
      <div className="stat">24</div>
      <div className="stat-desc">待办 12 · 进行中 5 · 完成 7</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">全部任务</div>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>准备项目评审</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-high">高</span>
      <span className="task-date">今天 14:00</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>更新接口文档</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-mid">中</span>
      <span className="task-date">今天</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>买猫粮</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-life">生活</span>
      <span className="task-tag priority-mid">中</span>
      <span className="task-date overdue">已逾期</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>整理房间</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-life">生活</span>
      <span className="task-tag priority-low">低</span>
      <span className="task-date">本周</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>复习 React 19 笔记</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-learning">学习</span>
      <span className="task-tag priority-mid">中</span>
      <span className="task-date">今天</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>优化首页加载速度</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-high">高</span>
      <span className="task-date overdue">已逾期</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <div className="task-body">
      <TaskText>修复登录页样式</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-mid">中</span>
      <span className="task-date">今天</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <div className="task-body">
      <TaskText>铲屎</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-life">生活</span>
      <span className="task-tag priority-low">低</span>
      <span className="task-date">今天</span>
      </div>
      </div>
      </ToggleRow>
      </section>
    </>
  )
}

export function TodayPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>今日任务</h1>
      <p>2026-09-20 星期日 · 3 / 8 完成</p>
      <div className="hero-meta">
      <span>高优先级：<strong>3</strong></span>
      <span>已逾期：<strong>2</strong></span>
      <span>剩余：<strong>5</strong></span>
      </div>
      </section>
      <section className="card">
      <div className="card-title">待办</div>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>准备项目评审</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-high">高</span>
      <span className="task-date">14:00</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>买猫粮</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-life">生活</span>
      <span className="task-date overdue">已逾期</span>
      </div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>复习 React 19 笔记</TaskText>
      <div className="task-meta">
      <span className="task-tag scope-learning">学习</span>
      </div>
      </div>
      </ToggleRow>
      </section>
      <section className="card">
      <div className="card-title">已完成</div>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>修复登录页样式</DoneText>
      <div className="done-time">10:30</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>铲屎</DoneText>
      <div className="done-time">08:15</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>写日报</DoneText>
      <div className="done-time">18:00</div>
      </ToggleRow>
      </section>
    </>
  )
}

export function InboxPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>收件箱 📥</h1>
      <p>快速收集，未分类、未整理的任务。</p>
      <div className="hero-meta">
      <span>未整理：<strong>5</strong></span>
      <span>今日新增：<strong>3</strong></span>
      </div>
      </section>
      <section className="card">
      <div className="quick-add">
      <input className="quick-input" placeholder="随手记，回车进入收件箱..." />
      <button className="btn btn-primary">添加</button>
      </div>
      </section>
      <section className="card">
      <div className="card-title">未整理</div>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>看看新的 React 19 文档</TaskText>
      <div className="task-meta"><span className="task-tag">未分类</span></div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>研究一下 Vite 插件</TaskText>
      <div className="task-meta"><span className="task-tag">未分类</span></div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>整理上周的工作记录</TaskText>
      <div className="task-meta"><span className="task-tag">未分类</span></div>
      </div>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <div className="task-body">
      <TaskText>想想国庆去哪玩</TaskText>
      <div className="task-meta"><span className="task-tag">未分类</span></div>
      </div>
      </ToggleRow>
      </section>
    </>
  )
}

export function BoardPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">任务看板</div>
      <div className="kanban">
      <div className="kanban-col">
      <div className="kanban-title"><span>待办</span><span>5</span></div>
      <div className="kanban-card">
      <div className="kanban-card-title">更新接口文档</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-work">工作</span>
      </div>
      </div>
      <div className="kanban-card">
      <div className="kanban-card-title">买猫粮</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-life">生活</span>
      <span className="task-tag priority-mid">中</span>
      </div>
      </div>
      <div className="kanban-card">
      <div className="kanban-card-title">整理房间</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-life">生活</span>
      </div>
      </div>
      <div className="kanban-card">
      <div className="kanban-card-title">复习 React 19</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-learning">学习</span>
      </div>
      </div>
      <div className="kanban-card">
      <div className="kanban-card-title">优化首页加载</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-high">高</span>
      </div>
      </div>
      </div>
      <div className="kanban-col">
      <div className="kanban-title"><span>进行中</span><span>3</span></div>
      <div className="kanban-card">
      <div className="kanban-card-title">准备项目评审</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-work">工作</span>
      <span className="task-tag priority-high">高</span>
      </div>
      </div>
      <div className="kanban-card">
      <div className="kanban-card-title">个人系统前端</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-learning">学习</span>
      </div>
      </div>
      <div className="kanban-card">
      <div className="kanban-card-title">弥散主题系统</div>
      <div className="kanban-card-meta">
      <span className="task-tag scope-learning">学习</span>
      </div>
      </div>
      </div>
      <div className="kanban-col">
      <div className="kanban-title"><span>已完成</span><span>4</span></div>
      <div className="kanban-card" style={{ opacity: "0.6" }}>
      <div className="kanban-card-title" style={{ textDecoration: "line-through" }}>修复登录页样式</div>
      </div>
      <div className="kanban-card" style={{ opacity: "0.6" }}>
      <div className="kanban-card-title" style={{ textDecoration: "line-through" }}>铲屎</div>
      </div>
      <div className="kanban-card" style={{ opacity: "0.6" }}>
      <div className="kanban-card-title" style={{ textDecoration: "line-through" }}>写日报</div>
      </div>
      <div className="kanban-card" style={{ opacity: "0.6" }}>
      <div className="kanban-card-title" style={{ textDecoration: "line-through" }}>搭 Vite 框架</div>
      </div>
      </div>
      </div>
      </section>
    </>
  )
}

export function MatrixPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">四象限</div>
      <div className="matrix">
      <div className="matrix-box">
      <div className="matrix-title">
      <span className="matrix-q1">🔥 重要紧急</span>
      <span>2</span>
      </div>
      <div className="matrix-item">准备项目评审</div>
      <div className="matrix-item">优化首页加载速度</div>
      </div>
      <div className="matrix-box">
      <div className="matrix-title">
      <span className="matrix-q2">📌 重要不紧急</span>
      <span>4</span>
      </div>
      <div className="matrix-item">更新接口文档</div>
      <div className="matrix-item">个人系统前端</div>
      <div className="matrix-item">复习 React 19</div>
      <div className="matrix-item">读 CSAPP</div>
      </div>
      <div className="matrix-box">
      <div className="matrix-title">
      <span className="matrix-q3">⏰ 紧急不重要</span>
      <span>3</span>
      </div>
      <div className="matrix-item">买猫粮</div>
      <div className="matrix-item">取快递</div>
      <div className="matrix-item">给爸妈打电话</div>
      </div>
      <div className="matrix-box">
      <div className="matrix-title">
      <span className="matrix-q4">☕ 不紧急不重要</span>
      <span>3</span>
      </div>
      <div className="matrix-item">整理房间</div>
      <div className="matrix-item">看剧</div>
      <div className="matrix-item">刷手机</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function CalendarPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">2026 年 9 月</div>
      <div className="calendar-grid">
      <div className="cal-head">一</div>
      <div className="cal-head">二</div>
      <div className="cal-head">三</div>
      <div className="cal-head">四</div>
      <div className="cal-head">五</div>
      <div className="cal-head">六</div>
      <div className="cal-head">日</div>
      <div className="cal-day muted"><div className="cal-day-num">31</div></div>
      <div className="cal-day"><div className="cal-day-num">1</div></div>
      <div className="cal-day"><div className="cal-day-num">2</div></div>
      <div className="cal-day"><div className="cal-day-num">3</div></div>
      <div className="cal-day"><div className="cal-day-num">4</div></div>
      <div className="cal-day"><div className="cal-day-num">5</div></div>
      <div className="cal-day"><div className="cal-day-num">6</div></div>
      <div className="cal-day"><div className="cal-day-num">7</div></div>
      <div className="cal-day"><div className="cal-day-num">8</div><div className="cal-task">接口文档</div></div>
      <div className="cal-day"><div className="cal-day-num">9</div></div>
      <div className="cal-day"><div className="cal-day-num">10</div></div>
      <div className="cal-day"><div className="cal-day-num">11</div></div>
      <div className="cal-day"><div className="cal-day-num">12</div></div>
      <div className="cal-day"><div className="cal-day-num">13</div></div>
      <div className="cal-day"><div className="cal-day-num">14</div></div>
      <div className="cal-day"><div className="cal-day-num">15</div></div>
      <div className="cal-day"><div className="cal-day-num">16</div><div className="cal-task">项目评审</div></div>
      <div className="cal-day"><div className="cal-day-num">17</div></div>
      <div className="cal-day"><div className="cal-day-num">18</div></div>
      <div className="cal-day"><div className="cal-day-num">19</div></div>
      <div className="cal-day today"><div className="cal-day-num">20</div><div className="cal-task">项目评审</div></div>
      <div className="cal-day"><div className="cal-day-num">21</div></div>
      <div className="cal-day"><div className="cal-day-num">22</div></div>
      <div className="cal-day"><div className="cal-day-num">23</div><div className="cal-task">疫苗</div></div>
      <div className="cal-day"><div className="cal-day-num">24</div></div>
      <div className="cal-day"><div className="cal-day-num">25</div></div>
      <div className="cal-day"><div className="cal-day-num">26</div></div>
      <div className="cal-day"><div className="cal-day-num">27</div></div>
      <div className="cal-day"><div className="cal-day-num">28</div></div>
      <div className="cal-day"><div className="cal-day-num">29</div></div>
      <div className="cal-day"><div className="cal-day-num">30</div></div>
      <div className="cal-day muted"><div className="cal-day-num">1</div></div>
      <div className="cal-day muted"><div className="cal-day-num">2</div></div>
      <div className="cal-day muted"><div className="cal-day-num">3</div></div>
      <div className="cal-day muted"><div className="cal-day-num">4</div></div>
      </div>
      </section>
    </>
  )
}

export function DonePanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">本周完成</div>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>修复登录页样式</DoneText>
      <div className="done-time">今天 10:30</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>铲屎</DoneText>
      <div className="done-time">今天 08:15</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>写日报</DoneText>
      <div className="done-time">今天 18:00</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>搭 Vite + React + TS 框架</DoneText>
      <div className="done-time">昨天</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>代码评审</DoneText>
      <div className="done-time">昨天</div>
      </ToggleRow>
      <ToggleRow className="done-item" defaultDone>
      <div className="task-check done">✓</div>
      <DoneText>买菜</DoneText>
      <div className="done-time">2 天前</div>
      </ToggleRow>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <button className="btn btn-ghost" id="aiAdd" onClick={() => handlers.aiAddOpen()}>✨ AI 拆解</button>
      <button className="btn btn-primary" id="newTaskBtn" onClick={() => handlers.newTaskBtnOpen()}>+ 新建任务</button>
    </>
  )
}

/** 弹窗体：原型 `newTaskBtn` 标题「新建任务」 */
export function NewTaskBtnModal({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <div className="form-field">
      <label className="form-label">任务标题</label>
      <input className="form-input" placeholder="要做什么..." />
      </div>
      <div className="form-field">
      <label className="form-label">领域</label>
      <select className="form-select">
      <option>生活</option>
      <option>工作</option>
      <option>学习</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">优先级</label>
      <select className="form-select" defaultValue="中">
      <option>高</option>
      <option>中</option>
      <option>低</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">截止时间</label>
      <input className="form-input" type="date" defaultValue="2026-09-20" />
      </div>
      <div className="form-field">
      <label className="form-label">关联项目</label>
      <select className="form-select">
      <option>无</option>
      <option>个人系统前端</option>
      <option>支付系统重构</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">备注</label>
      <textarea className="form-textarea" placeholder="补充说明..."></textarea>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>取消</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：已创建'); handlers.closeModal() }}>创建</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `aiAdd` 标题「✨ AI 拆解任务」 */
export function AiAddModal({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <div className="form-field">
      <label className="form-label">输入一句话，AI 帮你拆成子任务</label>
      <textarea className="form-textarea" placeholder="例如：上线个人系统前端"></textarea>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>取消</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：AI 拆解'); handlers.closeModal() }}>拆解</button>
      </div>
    </>
  )
}
