/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * knowledge 模块的面板与弹窗标记。
 *
 * 事实源：design/know/knowledge_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <KnowledgeWorkspace />（同目录）。
 */

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'notes', label: '全部笔记' },
  { key: 'topics', label: '主题' },
  { key: 'tags', label: '标签' },
  { key: 'graph', label: '双链图谱' },
  { key: 'favorites', label: '收藏' },
  { key: 'archive', label: '归档' },
]

/** 本模块所有交互回调 —— 实现写在 <KnowledgeWorkspace /> 里。 */
export interface Handlers {
  closeModal: () => void
  notice: (arg0: string) => void
  openNote: (arg0: string) => void
  openTopic: (arg0: string) => void
}

export const MODAL_SPECS = {
  openTopic: { title: null, arg: true },
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function NotesPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>知识库 📚</h1>
      <p>跨模块沉淀：学习笔记、工作脱敏知识、项目产出，统一在这里。</p>
      <div className="hero-meta">
      <span>笔记总数：<strong>286</strong></span>
      <span>主题：<strong>42</strong></span>
      <span>标签：<strong>96</strong></span>
      <span>本周新增：<strong>12</strong></span>
      </div>
      </section>
      <section className="card">
      <input className="search-input" placeholder="🔍 搜索笔记标题、内容、标签..." />
      </section>
      <section className="card">
      <div className="card-title">最近笔记</div>
      <div className="note-item" onClick={() => handlers.openNote('弥散风格 UI 设计要点')}>
      <div className="note-title">弥散风格 UI 设计要点</div>
      <div className="note-excerpt">弥散风格核心是低饱和色团 + 毛玻璃卡片。色团 blur 120px，透明度 0.35 左右，避免视觉趋同。</div>
      <div className="note-meta">
      <span className="note-tag">设计</span>
      <span className="note-tag">UI</span>
      <span className="note-time">2 小时前</span>
      </div>
      </div>
      <div className="note-item" onClick={() => handlers.openNote('React 19 新特性整理')}>
      <div className="note-title">React 19 新特性整理</div>
      <div className="note-excerpt">ref 可直接作为 prop，不再必须 forwardRef；Actions、use()、useOptimistic 等。</div>
      <div className="note-meta">
      <span className="note-tag">React</span>
      <span className="note-tag">前端</span>
      <span className="note-time">昨天</span>
      </div>
      </div>
      <div className="note-item" onClick={() => handlers.openNote('Vite 构建优化记录')}>
      <div className="note-title">Vite 构建优化记录</div>
      <div className="note-excerpt">通过 manualChunks 拆分 vendor，首屏构建从 12s 降到 6s。</div>
      <div className="note-meta">
      <span className="note-tag">Vite</span>
      <span className="note-tag">构建</span>
      <span className="note-time">2 天前</span>
      </div>
      </div>
      <div className="note-item" onClick={() => handlers.openNote('支付系统重构思路')}>
      <div className="note-title">支付系统重构思路</div>
      <div className="note-excerpt">核心是拆分支付链路，引入异步对账，减少同步依赖。已脱敏。</div>
      <div className="note-meta">
      <span className="note-tag">架构</span>
      <span className="note-tag">脱敏</span>
      <span className="note-time">3 天前</span>
      </div>
      </div>
      <div className="note-item" onClick={() => handlers.openNote('养猫经验：疫苗与驱虫')}>
      <div className="note-title">养猫经验：疫苗与驱虫</div>
      <div className="note-excerpt">幼猫 3 针疫苗，间隔 21 天；体内驱虫 3 个月一次，体外 1 个月一次。</div>
      <div className="note-meta">
      <span className="note-tag">生活</span>
      <span className="note-tag">宠物</span>
      <span className="note-time">5 天前</span>
      </div>
      </div>
      </section>
    </>
  )
}

export function TopicsPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">主题</div>
      <div className="topic-item" onClick={() => handlers.openTopic('前端工程化')}>
      <div className="topic-icon">⚛️</div>
      <div className="topic-info">
      <div className="topic-name">前端工程化</div>
      <div className="topic-meta">42 条笔记 · Vite / React / TS / 构建</div>
      </div>
      </div>
      <div className="topic-item" onClick={() => handlers.openTopic('后端架构')}>
      <div className="topic-icon">🏗️</div>
      <div className="topic-info">
      <div className="topic-name">后端架构</div>
      <div className="topic-meta">36 条笔记 · 支付 / 对账 / 分布式</div>
      </div>
      </div>
      <div className="topic-item" onClick={() => handlers.openTopic('UI 设计')}>
      <div className="topic-icon">🎨</div>
      <div className="topic-info">
      <div className="topic-name">UI 设计</div>
      <div className="topic-meta">28 条笔记 · 弥散 / 毛玻璃 / 配色</div>
      </div>
      </div>
      <div className="topic-item" onClick={() => handlers.openTopic('个人系统')}>
      <div className="topic-icon">🧩</div>
      <div className="topic-info">
      <div className="topic-name">个人系统</div>
      <div className="topic-meta">24 条笔记 · 模块 / 权限 / 数据模型</div>
      </div>
      </div>
      <div className="topic-item" onClick={() => handlers.openTopic('养猫')}>
      <div className="topic-icon">🐱</div>
      <div className="topic-info">
      <div className="topic-name">养猫</div>
      <div className="topic-meta">18 条笔记 · 疫苗 / 驱虫 / 饮食</div>
      </div>
      </div>
      <div className="topic-item" onClick={() => handlers.openTopic('健身与饮食')}>
      <div className="topic-icon">🏃</div>
      <div className="topic-info">
      <div className="topic-name">健身与饮食</div>
      <div className="topic-meta">16 条笔记 · 训练 / 食谱 / 减脂</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function TagsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">标签云</div>
      <div className="tag-cloud">
      <span className="tag-item xl">React</span>
      <span className="tag-item lg">Vite</span>
      <span className="tag-item">TypeScript</span>
      <span className="tag-item lg">CSS</span>
      <span className="tag-item xl">架构</span>
      <span className="tag-item">支付</span>
      <span className="tag-item lg">UI</span>
      <span className="tag-item">弥散</span>
      <span className="tag-item">毛玻璃</span>
      <span className="tag-item lg">养猫</span>
      <span className="tag-item">宠物</span>
      <span className="tag-item">健身</span>
      <span className="tag-item lg">食谱</span>
      <span className="tag-item">减脂</span>
      <span className="tag-item">睡眠</span>
      <span className="tag-item lg">个人系统</span>
      <span className="tag-item">数据模型</span>
      <span className="tag-item">权限</span>
      <span className="tag-item">脱敏</span>
      <span className="tag-item lg">Vite</span>
      </div>
      </section>
    </>
  )
}

export function GraphPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">双链图谱</div>
      <div className="graph-canvas">
      <div className="graph-node center" style={{ top: "110px", left: "calc(50% - 40px)" }}>个人系统</div>
      <div className="graph-node" style={{ top: "30px", left: "40px" }}>React</div>
      <div className="graph-node" style={{ top: "30px", right: "40px" }}>Vite</div>
      <div className="graph-node" style={{ bottom: "30px", left: "60px" }}>UI 设计</div>
      <div className="graph-node" style={{ bottom: "30px", right: "60px" }}>架构</div>
      <div className="graph-node" style={{ top: "130px", left: "20px" }}>TypeScript</div>
      <div className="graph-node" style={{ top: "130px", right: "20px" }}>CSS</div>
      </div>
      <div className="notice" style={{ marginTop: "12px" }}>
      节点大小代表笔记数量，连线代表双向链接。点击节点可查看关联笔记。
      </div>
      </section>
    </>
  )
}

export function FavoritesPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">收藏</div>
      <div className="favorite-item" onClick={() => handlers.openNote('弥散风格 UI 设计要点')}>
      <div className="favorite-icon">⭐</div>
      <div className="favorite-info">
      <div className="favorite-name">弥散风格 UI 设计要点</div>
      <div className="favorite-meta">设计 / UI · 收藏于 2 天前</div>
      </div>
      </div>
      <div className="favorite-item" onClick={() => handlers.openNote('React 19 新特性整理')}>
      <div className="favorite-icon">⭐</div>
      <div className="favorite-info">
      <div className="favorite-name">React 19 新特性整理</div>
      <div className="favorite-meta">React / 前端 · 收藏于 3 天前</div>
      </div>
      </div>
      <div className="favorite-item" onClick={() => handlers.openNote('支付系统重构思路')}>
      <div className="favorite-icon">⭐</div>
      <div className="favorite-info">
      <div className="favorite-name">支付系统重构思路</div>
      <div className="favorite-meta">架构 / 脱敏 · 收藏于 5 天前</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function ArchivePanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">归档</div>
      <div className="note-item">
      <div className="note-title">2024 年技术总结</div>
      <div className="note-excerpt">已归档，保留历史。</div>
      <div className="note-meta">
      <span className="note-tag">归档</span>
      <span className="note-time">2025-01-10</span>
      </div>
      </div>
      <div className="note-item">
      <div className="note-title">旧版个人系统设计</div>
      <div className="note-excerpt">已被新版替代。</div>
      <div className="note-meta">
      <span className="note-tag">归档</span>
      <span className="note-time">2026-06-15</span>
      </div>
      </div>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <button className="btn btn-ghost" id="quickAdd" onClick={() => handlers.notice('原型演示：新建笔记')}>+ 新建笔记</button>
    </>
  )
}

/** 弹窗体：原型 `openTopic` 标题由触发参数决定 */
export function OpenTopicModal({ handlers, name }: { handlers: Handlers; name: string }) {
  return (
    <>
      <div className="detail-section">
      <div className="detail-label">主题说明</div>
      <div className="detail-text">这是「{name}」主题下的笔记集合，按时间倒序排列。</div>
      </div>
      <div className="detail-section">
      <div className="detail-label">笔记列表</div>
      <ul className="detail-list">
      <li>最近更新笔记 1</li>
      <li>最近更新笔记 2</li>
      <li>最近更新笔记 3</li>
      </ul>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-primary" onClick={() => handlers.notice('原型演示：新建笔记')}>+ 新建笔记</button>
      </div>
    </>
  )
}
