/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * work 模块的面板与弹窗标记。
 *
 * 事实源：design/work/work_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <WorkWorkspace />（同目录）。
 */

import { ToggleRow, TaskCheck, TaskText } from '../../../components/workspace/toggles'

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'dashboard', label: '工作台' },
  { key: 'tasks', label: '任务' },
  { key: 'projects', label: '项目' },
  { key: 'servers', label: '服务器' },
  { key: 'deploy', label: '部署' },
  { key: 'calendar', label: '日历会议' },
  { key: 'docs', label: '文档索引' },
  { key: 'contacts', label: '联系人' },
  { key: 'clients', label: '客户资料' },
  { key: 'okr', label: 'OKR/KPI' },
  { key: 'timesheet', label: '工时' },
  { key: 'review', label: '周报复盘' },
]

/** 本模块所有交互回调 —— 实现写在 <WorkWorkspace /> 里。 */
export interface Handlers {
  notice: (arg0: string) => void
  openClient: (arg0: string) => void
}

export const MODAL_SPECS = {
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function DashboardPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>下午好，杨刘 👋</h1>
      <p>今天是 2026-09-20 星期日，本周还有 1 天。</p>
      <div className="hero-meta">
      <span>今日任务：<strong>3 / 8</strong></span>
      <span>今日会议：<strong>2 场</strong></span>
      <span>进行项目：<strong>4 个</strong></span>
      <span>本周工时：<strong>32h</strong></span>
      </div>
      </section>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">今日任务</div>
      <div className="stat">3 / 8</div>
      <div className="stat-desc">2 个高优先级 · 1 个逾期</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}><div className="progress-fill" style={{ width: "38%" }}></div></div>
      </div>
      <div className="card">
      <div className="card-title">今日会议</div>
      <div className="stat">2</div>
      <div className="stat-desc">下一场 14:00 项目评审</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}><div className="progress-fill" style={{ width: "40%" }}></div></div>
      </div>
      <div className="card">
      <div className="card-title">本周工时</div>
      <div className="stat">32h</div>
      <div className="stat-desc">目标 40h · 80%</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}><div className="progress-fill" style={{ width: "80%" }}></div></div>
      </div>
      </section>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">今日任务</div>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>修复登录页样式</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>代码评审</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>写日报</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>准备项目评审</TaskText>
      <span className="task-tag">进行中</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>更新接口文档</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      </div>
      <div className="card">
      <div className="card-title">今日会议</div>
      <div className="meeting-item">
      <div className="meeting-time">10:00</div>
      <div className="meeting-info">
      <div className="meeting-title">每日站会</div>
      <div className="meeting-meta">30 分钟 · 线上</div>
      </div>
      </div>
      <div className="meeting-item">
      <div className="meeting-time">14:00</div>
      <div className="meeting-info">
      <div className="meeting-title">项目评审</div>
      <div className="meeting-meta">60 分钟 · 会议室 A</div>
      </div>
      </div>
      </div>
      </section>
      <section className="grid-2">
      <div className="card">
      <div className="card-title">进行中项目</div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">支付系统重构</div>
      <div className="doc-meta">进度 62% · 截止 10-31</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">用户中心改版</div>
      <div className="doc-meta">进度 38% · 截止 11-15</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">数据看板</div>
      <div className="doc-meta">进度 80% · 截止 09-30</div>
      </div>
      </div>
      </div>
      <div className="card">
      <div className="card-title">最近文档</div>
      <div className="doc-item">
      <div className="doc-icon">📄</div>
      <div className="doc-info">
      <div className="doc-name">支付系统重构方案</div>
      <div className="doc-meta">更新于昨天</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📘</div>
      <div className="doc-info">
      <div className="doc-name">接口设计规范</div>
      <div className="doc-meta">更新于 3 天前</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">周会纪要 09-18</div>
      <div className="doc-meta">更新于 2 天前</div>
      </div>
      </div>
      </div>
      </section>
    </>
  )
}

export function TasksPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">工作任务</div>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>修复登录页样式</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <div className="task-check done">✓</div>
      <TaskText>代码评审</TaskText>
      <span className="task-tag">已完成</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>准备项目评审</TaskText>
      <span className="task-tag">进行中</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>更新接口文档</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>优化首页加载速度</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      <ToggleRow className="task-item">
      <TaskCheck />
      <TaskText>排查线上告警</TaskText>
      <span className="task-tag">待办</span>
      </ToggleRow>
      </section>
    </>
  )
}

export function ProjectsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">工作项目</div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">支付系统重构</div>
      <div className="doc-meta">进度 62% · 负责人：我 · 截止 10-31</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">用户中心改版</div>
      <div className="doc-meta">进度 38% · 负责人：我 · 截止 11-15</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">数据看板</div>
      <div className="doc-meta">进度 80% · 负责人：我 · 截止 09-30</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📦</div>
      <div className="doc-info">
      <div className="doc-name">性能优化专项</div>
      <div className="doc-meta">进度 20% · 负责人：我 · 截止 12-15</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function ServersPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">服务器总数</div>
      <div className="stat">8</div>
      <div className="stat-desc">生产 3 · 测试 3 · 预发 2</div>
      </div>
      <div className="card">
      <div className="card-title">运行中</div>
      <div className="stat" style={{ color: "#10B981" }}>7</div>
      <div className="stat-desc">1 台已停止</div>
      </div>
      <div className="card">
      <div className="card-title">即将到期</div>
      <div className="stat" style={{ color: "#F59E0B" }}>1</div>
      <div className="stat-desc">30 天内</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">生产环境</div>
      <div className="server-item">
      <div className="server-env">生产</div>
      <div className="server-info">
      <div className="server-name">prod-web-01</div>
      <div className="server-meta">47.100.x.x · 阿里云 · 4C8G · Ubuntu 22.04</div>
      </div>
      <span className="server-status">运行中</span>
      </div>
      <div className="server-item">
      <div className="server-env">生产</div>
      <div className="server-info">
      <div className="server-name">prod-db-01</div>
      <div className="server-meta">47.100.x.x · 阿里云 · 8C16G · Ubuntu 22.04</div>
      </div>
      <span className="server-status">运行中</span>
      </div>
      <div className="server-item">
      <div className="server-env">生产</div>
      <div className="server-info">
      <div className="server-name">prod-cache-01</div>
      <div className="server-meta">47.100.x.x · 阿里云 · 2C4G · Ubuntu 22.04</div>
      </div>
      <span className="server-status">运行中</span>
      </div>
      </section>
      <section className="card">
      <div className="card-title">测试环境</div>
      <div className="server-item">
      <div className="server-env">测试</div>
      <div className="server-info">
      <div className="server-name">test-web-01</div>
      <div className="server-meta">10.0.1.x · 内网 · 2C4G · Ubuntu 22.04</div>
      </div>
      <span className="server-status">运行中</span>
      </div>
      <div className="server-item">
      <div className="server-env">测试</div>
      <div className="server-info">
      <div className="server-name">test-db-01</div>
      <div className="server-meta">10.0.1.x · 内网 · 4C8G · Ubuntu 22.04</div>
      </div>
      <span className="server-status">运行中</span>
      </div>
      <div className="server-item">
      <div className="server-env">测试</div>
      <div className="server-info">
      <div className="server-name">test-job-01</div>
      <div className="server-meta">10.0.1.x · 内网 · 2C4G · Ubuntu 22.04</div>
      </div>
      <span className="server-status">已停止</span>
      </div>
      </section>
      <section className="card">
      <div className="card-title" style={{ color: "var(--mw-m-main)" }}>安全提示</div>
      <div className="notice">
      密码、密钥不存明文，只存引用；生产 IP 脱敏；敏感信息走公司密钥管理工具。
      </div>
      </section>
    </>
  )
}

export function DeployPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">部署文档</div>
      <div className="doc-item">
      <div className="doc-icon">🚀</div>
      <div className="doc-info">
      <div className="doc-name">生产环境部署手册</div>
      <div className="doc-meta">部署 · 生产 · v2.3 · 更新于昨天</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">🔙</div>
      <div className="doc-info">
      <div className="doc-name">回滚流程</div>
      <div className="doc-meta">回滚 · 生产 · v1.2 · 更新于 3 天前</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">⚙️</div>
      <div className="doc-info">
      <div className="doc-name">环境变量配置</div>
      <div className="doc-meta">配置 · 生产 · v1.0 · 更新于 1 周前</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">✅</div>
      <div className="doc-info">
      <div className="doc-name">发布检查清单</div>
      <div className="doc-meta">检查清单 · 生产 · v1.1 · 更新于 2 天前</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📜</div>
      <div className="doc-info">
      <div className="doc-name">部署脚本 deploy.sh</div>
      <div className="doc-meta">脚本 · 生产 · v1.4 · 更新于 5 天前</div>
      </div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">部署记录</div>
      <div className="timesheet-row">
      <span>2026-09-20 · v2.3.1</span>
      <span className="deploy-status success">成功</span>
      </div>
      <div className="timesheet-row">
      <span>2026-09-15 · v2.3.0</span>
      <span className="deploy-status success">成功</span>
      </div>
      <div className="timesheet-row">
      <span>2026-09-10 · v2.2.9</span>
      <span className="deploy-status rollback">回滚</span>
      </div>
      <div className="timesheet-row">
      <span>2026-09-05 · v2.2.8</span>
      <span className="deploy-status success">成功</span>
      </div>
      </section>
      <section className="card">
      <div className="card-title" style={{ color: "var(--mw-m-main)" }}>注意</div>
      <div className="notice">
      部署文档正文留在公司 Wiki，个人系统只存索引、链接、脱敏摘要；服务器和部署按项目走。
      </div>
      </section>
    </>
  )
}

export function CalendarPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">今日会议</div>
      <div className="meeting-item">
      <div className="meeting-time">10:00</div>
      <div className="meeting-info">
      <div className="meeting-title">每日站会</div>
      <div className="meeting-meta">30 分钟 · 线上</div>
      </div>
      </div>
      <div className="meeting-item">
      <div className="meeting-time">14:00</div>
      <div className="meeting-info">
      <div className="meeting-title">项目评审</div>
      <div className="meeting-meta">60 分钟 · 会议室 A</div>
      </div>
      </div>
      <div className="meeting-item">
      <div className="meeting-time">16:30</div>
      <div className="meeting-info">
      <div className="meeting-title">一对一沟通</div>
      <div className="meeting-meta">30 分钟 · 线上</div>
      </div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">本周会议</div>
      <div className="meeting-item">
      <div className="meeting-time">周一</div>
      <div className="meeting-info">
      <div className="meeting-title">周会</div>
      <div className="meeting-meta">60 分钟</div>
      </div>
      </div>
      <div className="meeting-item">
      <div className="meeting-time">周三</div>
      <div className="meeting-info">
      <div className="meeting-title">技术分享</div>
      <div className="meeting-meta">90 分钟</div>
      </div>
      </div>
      <div className="meeting-item">
      <div className="meeting-time">周五</div>
      <div className="meeting-info">
      <div className="meeting-title">项目复盘</div>
      <div className="meeting-meta">60 分钟</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function DocsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">文档索引</div>
      <div className="doc-item">
      <div className="doc-icon">📄</div>
      <div className="doc-info">
      <div className="doc-name">支付系统重构方案</div>
      <div className="doc-meta">Wiki · 更新于昨天</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📘</div>
      <div className="doc-info">
      <div className="doc-name">接口设计规范</div>
      <div className="doc-meta">Wiki · 更新于 3 天前</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📝</div>
      <div className="doc-info">
      <div className="doc-name">周会纪要 09-18</div>
      <div className="doc-meta">会议纪要 · 更新于 2 天前</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">🔗</div>
      <div className="doc-info">
      <div className="doc-name">GitLab 仓库</div>
      <div className="doc-meta">外部链接</div>
      </div>
      </div>
      </section>
      <section className="card">
      <div className="card-title" style={{ color: "var(--mw-m-main)" }}>注意</div>
      <div className="notice">
      工作文档正文留在公司工具，个人系统只存索引、链接、脱敏摘要。
      </div>
      </section>
    </>
  )
}

export function ContactsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">联系人</div>
      <div className="contact-item">
      <div className="avatar">张</div>
      <div className="contact-info">
      <div className="contact-name">张工</div>
      <div className="contact-meta">技术负责人</div>
      </div>
      </div>
      <div className="contact-item">
      <div className="avatar">李</div>
      <div className="contact-info">
      <div className="contact-name">李工</div>
      <div className="contact-meta">前端同事</div>
      </div>
      </div>
      <div className="contact-item">
      <div className="avatar">王</div>
      <div className="contact-info">
      <div className="contact-name">王产品</div>
      <div className="contact-meta">产品经理</div>
      </div>
      </div>
      <div className="contact-item">
      <div className="avatar">赵</div>
      <div className="contact-info">
      <div className="contact-name">赵测试</div>
      <div className="contact-meta">测试同事</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function ClientsPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">客户数</div>
      <div className="stat">8</div>
      <div className="stat-desc">本周新增 2 个</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}>
      <div className="progress-fill" style={{ width: "60%" }}></div>
      </div>
      </div>
      <div className="card">
      <div className="card-title">资料文件</div>
      <div className="stat">126</div>
      <div className="stat-desc">Excel 48 · MD 32 · PDF 26</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}>
      <div className="progress-fill" style={{ width: "72%" }}></div>
      </div>
      </div>
      <div className="card">
      <div className="card-title">待整理</div>
      <div className="stat">5</div>
      <div className="stat-desc">未归类 / 未解读</div>
      <div className="progress-bar" style={{ marginTop: "8px" }}>
      <div className="progress-fill" style={{ width: "30%" }}></div>
      </div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">客户资料库</div>
      <div className="client-card" onClick={() => handlers.openClient('星辰科技')}>
      <div className="client-avatar">星</div>
      <div className="client-info">
      <div className="client-name">星辰科技</div>
      <div className="client-meta">32 个文件 · 最近更新 2 小时前</div>
      <div className="client-tags">
      <span className="client-tag">需求 12</span>
      <span className="client-tag">数据 8</span>
      <span className="client-tag">原型 6</span>
      </div>
      </div>
      <div className="client-right">
      <div className="client-amount">32</div>
      <div className="client-status">文件</div>
      </div>
      </div>
      <div className="client-card" onClick={() => handlers.openClient('云启网络')}>
      <div className="client-avatar">云</div>
      <div className="client-info">
      <div className="client-name">云启网络</div>
      <div className="client-meta">18 个文件 · 最近更新 昨天</div>
      <div className="client-tags">
      <span className="client-tag">需求 8</span>
      <span className="client-tag">参考 5</span>
      </div>
      </div>
      <div className="client-right">
      <div className="client-amount">18</div>
      <div className="client-status">文件</div>
      </div>
      </div>
      <div className="client-card" onClick={() => handlers.openClient('蓝海数据')}>
      <div className="client-avatar">蓝</div>
      <div className="client-info">
      <div className="client-name">蓝海数据</div>
      <div className="client-meta">46 个文件 · 最近更新 3 天前</div>
      <div className="client-tags">
      <span className="client-tag">数据 24</span>
      <span className="client-tag">合同 4</span>
      </div>
      </div>
      <div className="client-right">
      <div className="client-amount">46</div>
      <div className="client-status">文件</div>
      </div>
      </div>
      <div className="client-card" onClick={() => handlers.openClient('微光传媒')}>
      <div className="client-avatar">微</div>
      <div className="client-info">
      <div className="client-name">微光传媒</div>
      <div className="client-meta">12 个文件 · 最近更新 5 天前</div>
      <div className="client-tags">
      <span className="client-tag">需求 6</span>
      <span className="client-tag">原型 4</span>
      </div>
      </div>
      <div className="client-right">
      <div className="client-amount">12</div>
      <div className="client-status">文件</div>
      </div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">最近资料</div>
      <div className="doc-item">
      <div className="doc-icon">📊</div>
      <div className="doc-info">
      <div className="doc-name">需求清单 v3.xlsx</div>
      <div className="doc-meta">星辰科技 · 2 小时前 · 1.2 MB</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📄</div>
      <div className="doc-info">
      <div className="doc-name">接口说明.md</div>
      <div className="doc-meta">云启网络 · 昨天 · 24 KB</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">📕</div>
      <div className="doc-info">
      <div className="doc-name">数据字典.pdf</div>
      <div className="doc-meta">蓝海数据 · 3 天前 · 3.4 MB</div>
      </div>
      </div>
      <div className="doc-item">
      <div className="doc-icon">🖼️</div>
      <div className="doc-info">
      <div className="doc-name">首页原型.png</div>
      <div className="doc-meta">微光传媒 · 5 天前 · 860 KB</div>
      </div>
      </div>
      </section>
    </>
  )
}

export function OkrPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">2026 Q3 OKR</div>
      <div className="okr-item">
      <div className="okr-title">O1：提升系统稳定性</div>
      <div className="okr-desc">KR1：线上故障数下降 50%</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "70%" }}></div></div>
      <div className="progress-label"><span>70%</span><span>目标 50% 下降</span></div>
      </div>
      <div className="okr-item">
      <div className="okr-title">O2：交付支付系统重构</div>
      <div className="okr-desc">KR1：完成核心链路重构</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "62%" }}></div></div>
      <div className="progress-label"><span>62%</span><span>截止 10-31</span></div>
      </div>
      <div className="okr-item">
      <div className="okr-title">O3：提升团队效率</div>
      <div className="okr-desc">KR1：CI 构建时间缩短 40%</div>
      <div className="progress-bar"><div className="progress-fill" style={{ width: "45%" }}></div></div>
      <div className="progress-label"><span>45%</span><span>目标 40% 缩短</span></div>
      </div>
      </section>
    </>
  )
}

export function TimesheetPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="grid-3">
      <div className="card">
      <div className="card-title">本周工时</div>
      <div className="stat">32h</div>
      <div className="stat-desc">目标 40h</div>
      </div>
      <div className="card">
      <div className="card-title">本月工时</div>
      <div className="stat">142h</div>
      <div className="stat-desc">平均 8h / 天</div>
      </div>
      <div className="card">
      <div className="card-title">加班</div>
      <div className="stat">6h</div>
      <div className="stat-desc">本月</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">本周明细</div>
      <div className="timesheet-row">
      <span>支付系统重构</span>
      <span className="timesheet-value">14h</span>
      </div>
      <div className="timesheet-row">
      <span>用户中心改版</span>
      <span className="timesheet-value">8h</span>
      </div>
      <div className="timesheet-row">
      <span>数据看板</span>
      <span className="timesheet-value">5h</span>
      </div>
      <div className="timesheet-row">
      <span>会议</span>
      <span className="timesheet-value">3h</span>
      </div>
      <div className="timesheet-row">
      <span>代码评审</span>
      <span className="timesheet-value">2h</span>
      </div>
      </section>
    </>
  )
}

export function ReviewPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="review-block">
      <div className="review-label">本周完成</div>
      <ul className="review-list">
      <li>完成支付系统重构方案评审</li>
      <li>修复登录页样式问题</li>
      <li>完成 3 次代码评审</li>
      <li>更新接口设计规范</li>
      </ul>
      </div>
      <div className="review-block">
      <div className="review-label">下周计划</div>
      <ul className="review-list">
      <li>支付系统核心链路重构</li>
      <li>用户中心改版接口联调</li>
      <li>数据看板验收</li>
      </ul>
      </div>
      <div className="review-block">
      <div className="review-label">问题与阻塞</div>
      <ul className="review-list">
      <li>支付系统依赖第三方接口，联调延迟</li>
      <li>用户中心改版需求有变更</li>
      </ul>
      </div>
      <div className="review-block">
      <div className="review-label">经验沉淀</div>
      <ul className="review-list">
      <li>重构前先做接口梳理，减少返工</li>
      <li>代码评审提前介入，效果更好</li>
      </ul>
      </div>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <button className="btn btn-ghost" id="quickAdd" onClick={() => handlers.notice('原型演示：快速记录')}>+ 快速记录</button>
    </>
  )
}
