/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * calendar 模块的面板与弹窗标记。
 *
 * 事实源：design/candle/candle_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <CalendarWorkspace />（同目录）。
 */

import { Switch } from '../../../components/workspace/toggles'

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'month', label: '月视图' },
  { key: 'week', label: '周视图' },
  { key: 'day', label: '日视图' },
  { key: 'agenda', label: '议程' },
  { key: 'subscribe', label: '日历订阅' },
  { key: 'settings', label: '日程设置' },
]

/** 本模块所有交互回调 —— 实现写在 <CalendarWorkspace /> 里。 */
export interface Handlers {
  aiAddOpen: () => void
  closeModal: () => void
  newEventBtnOpen: () => void
  notice: (arg0: string) => void
  openEvent: (arg0: string) => void
}

export const MODAL_SPECS = {
  newEventBtn: { title: '新建日程' },
  aiAdd: { title: '✨ AI 找空闲' },
  openEvent: { title: null, arg: true },
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function MonthPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>日程 📅</h1>
      <p>统一时间轴，聚合生活、工作、学习、项目。</p>
      <div className="hero-meta">
      <span>今日：<strong>3 个事件</strong></span>
      <span>本周：<strong>12 个事件</strong></span>
      <span>下一场：<strong>14:00 项目评审</strong></span>
      </div>
      </section>
      <section className="card">
      <div className="cal-control" style={{ marginBottom: "16px" }}>
      <div className="cal-nav">
      <div className="cal-nav-btn" onClick={() => handlers.notice('原型演示：上个月')}>‹</div>
      <div className="cal-nav-btn" onClick={() => handlers.notice('原型演示：下个月')}>›</div>
      </div>
      <div className="cal-title">2026 年 9 月</div>
      <button className="btn btn-ghost" style={{ marginLeft: "auto" }} onClick={() => handlers.notice('原型演示：回到今天')}>今天</button>
      </div>
      <div className="month-grid">
      <div className="month-head">一</div>
      <div className="month-head">二</div>
      <div className="month-head">三</div>
      <div className="month-head">四</div>
      <div className="month-head">五</div>
      <div className="month-head">六</div>
      <div className="month-head">日</div>
      <div className="month-day muted"><div className="month-day-num">31</div></div>
      <div className="month-day"><div className="month-day-num">1</div></div>
      <div className="month-day"><div className="month-day-num">2</div></div>
      <div className="month-day"><div className="month-day-num">3</div><div className="month-event work">站会</div></div>
      <div className="month-day"><div className="month-day-num">4</div></div>
      <div className="month-day"><div className="month-day-num">5</div><div className="month-event life">家庭聚餐</div></div>
      <div className="month-day"><div className="month-day-num">6</div></div>
      <div className="month-day"><div className="month-day-num">7</div></div>
      <div className="month-day"><div className="month-day-num">8</div><div className="month-event work">评审</div></div>
      <div className="month-day"><div className="month-day-num">9</div></div>
      <div className="month-day"><div className="month-day-num">10</div></div>
      <div className="month-day"><div className="month-day-num">11</div></div>
      <div className="month-day"><div className="month-day-num">12</div><div className="month-event learning">技术分享</div></div>
      <div className="month-day"><div className="month-day-num">13</div></div>
      <div className="month-day"><div className="month-day-num">14</div></div>
      <div className="month-day"><div className="month-day-num">15</div><div className="month-event work">周会</div></div>
      <div className="month-day"><div className="month-day-num">16</div></div>
      <div className="month-day"><div className="month-day-num">17</div></div>
      <div className="month-day"><div className="month-day-num">18</div></div>
      <div className="month-day"><div className="month-day-num">19</div><div className="month-event life">运动</div></div>
      <div className="month-day today">
      <div className="month-day-num">20</div>
      <div className="month-event work">站会</div>
      <div className="month-event work">评审</div>
      <div className="month-event life">运动</div>
      </div>
      <div className="month-day"><div className="month-day-num">21</div></div>
      <div className="month-day"><div className="month-day-num">22</div></div>
      <div className="month-day"><div className="month-day-num">23</div><div className="month-event life">宠物疫苗</div></div>
      <div className="month-day"><div className="month-day-num">24</div></div>
      <div className="month-day"><div className="month-day-num">25</div></div>
      <div className="month-day"><div className="month-day-num">26</div></div>
      <div className="month-day"><div className="month-day-num">27</div></div>
      <div className="month-day"><div className="month-day-num">28</div></div>
      <div className="month-day"><div className="month-day-num">29</div></div>
      <div className="month-day"><div className="month-day-num">30</div><div className="month-event work">月会</div></div>
      <div className="month-day muted"><div className="month-day-num">1</div></div>
      <div className="month-day muted"><div className="month-day-num">2</div></div>
      <div className="month-day muted"><div className="month-day-num">3</div></div>
      <div className="month-day muted"><div className="month-day-num">4</div></div>
      </div>
      </section>
    </>
  )
}

export function WeekPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="cal-control" style={{ marginBottom: "16px" }}>
      <div className="cal-nav">
      <div className="cal-nav-btn" onClick={() => handlers.notice('原型演示：上周')}>‹</div>
      <div className="cal-nav-btn" onClick={() => handlers.notice('原型演示：下周')}>›</div>
      </div>
      <div className="cal-title">2026-09-14 ~ 2026-09-20</div>
      <button className="btn btn-ghost" style={{ marginLeft: "auto" }}>今天</button>
      </div>
      <div className="week-grid">
      <div className="week-head"></div>
      <div className="week-head">周一</div>
      <div className="week-head">周二</div>
      <div className="week-head">周三</div>
      <div className="week-head">周四</div>
      <div className="week-head">周五</div>
      <div className="week-head">周六</div>
      <div className="week-head today">周日</div>
      <div className="week-time">09:00</div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-time">10:00</div>
      <div className="week-cell"><div className="week-event work">周会</div></div>
      <div className="week-cell"></div>
      <div className="week-cell"><div className="week-event learning">技术分享</div></div>
      <div className="week-cell"></div>
      <div className="week-cell"><div className="week-event work">站会</div></div>
      <div className="week-cell"></div>
      <div className="week-cell"><div className="week-event work">站会</div></div>
      <div className="week-time">12:00</div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"><div className="week-event life">运动</div></div>
      <div className="week-cell"></div>
      <div className="week-time">14:00</div>
      <div className="week-cell"></div>
      <div className="week-cell"><div className="week-event work">评审</div></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"><div className="week-event work">项目评审</div></div>
      <div className="week-time">16:00</div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      <div className="week-cell"></div>
      </div>
      </section>
    </>
  )
}

export function DayPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card hero">
      <h1>2026-09-20 星期日</h1>
      <p>今天有 3 个事件，下一场 14:00 项目评审。</p>
      </section>
      <section className="card">
      <div className="card-title">今日日程</div>
      <div className="day-list">
      <div className="day-event work" onClick={() => handlers.openEvent('每日站会')}>
      <div className="day-event-time">10:00 - 10:30</div>
      <div className="day-event-info">
      <div className="day-event-title">每日站会</div>
      <div className="day-event-meta">
      <span className="day-event-tag">工作</span>
      <span>线上</span>
      <span>30 分钟</span>
      </div>
      </div>
      </div>
      <div className="day-event work" onClick={() => handlers.openEvent('项目评审')}>
      <div className="day-event-time">14:00 - 15:00</div>
      <div className="day-event-info">
      <div className="day-event-title">项目评审</div>
      <div className="day-event-meta">
      <span className="day-event-tag">工作</span>
      <span>会议室 A</span>
      <span>60 分钟</span>
      </div>
      </div>
      </div>
      <div className="day-event life" onClick={() => handlers.openEvent('运动')}>
      <div className="day-event-time">18:30 - 19:00</div>
      <div className="day-event-info">
      <div className="day-event-title">运动</div>
      <div className="day-event-meta">
      <span className="day-event-tag">生活</span>
      <span>跑步</span>
      <span>30 分钟</span>
      </div>
      </div>
      </div>
      </div>
      </section>
    </>
  )
}

export function AgendaPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="agenda-group">
      <div className="agenda-date">今天 · 2026-09-20</div>
      <div className="day-event work" onClick={() => handlers.openEvent('每日站会')}>
      <div className="day-event-time">10:00</div>
      <div className="day-event-info">
      <div className="day-event-title">每日站会</div>
      <div className="day-event-meta"><span className="day-event-tag">工作</span><span>线上</span></div>
      </div>
      </div>
      <div className="day-event work" onClick={() => handlers.openEvent('项目评审')}>
      <div className="day-event-time">14:00</div>
      <div className="day-event-info">
      <div className="day-event-title">项目评审</div>
      <div className="day-event-meta"><span className="day-event-tag">工作</span><span>会议室 A</span></div>
      </div>
      </div>
      <div className="day-event life" onClick={() => handlers.openEvent('运动')}>
      <div className="day-event-time">18:30</div>
      <div className="day-event-info">
      <div className="day-event-title">运动</div>
      <div className="day-event-meta"><span className="day-event-tag">生活</span><span>跑步</span></div>
      </div>
      </div>
      </div>
      <div className="agenda-group">
      <div className="agenda-date">明天 · 2026-09-21</div>
      <div className="day-event work" onClick={() => handlers.openEvent('周会')}>
      <div className="day-event-time">10:00</div>
      <div className="day-event-info">
      <div className="day-event-title">周会</div>
      <div className="day-event-meta"><span className="day-event-tag">工作</span><span>60 分钟</span></div>
      </div>
      </div>
      </div>
      <div className="agenda-group">
      <div className="agenda-date">周三 · 2026-09-23</div>
      <div className="day-event life" onClick={() => handlers.openEvent('宠物疫苗')}>
      <div className="day-event-time">全天</div>
      <div className="day-event-info">
      <div className="day-event-title">团子疫苗 + 驱虫</div>
      <div className="day-event-meta"><span className="day-event-tag">生活</span><span>宠物</span></div>
      </div>
      </div>
      </div>
      <div className="agenda-group">
      <div className="agenda-date">周五 · 2026-09-25</div>
      <div className="day-event work" onClick={() => handlers.openEvent('项目复盘')}>
      <div className="day-event-time">15:00</div>
      <div className="day-event-info">
      <div className="day-event-title">项目复盘</div>
      <div className="day-event-meta"><span className="day-event-tag">工作</span><span>60 分钟</span></div>
      </div>
      </div>
      </div>
      </section>
    </>
  )
}

export function SubscribePanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">订阅的日历</div>
      <div className="subscribe-item">
      <div className="subscribe-icon">📅</div>
      <div className="subscribe-info">
      <div className="subscribe-name">Google Calendar</div>
      <div className="subscribe-meta">已连接 · 同步中</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="subscribe-item">
      <div className="subscribe-icon">📅</div>
      <div className="subscribe-info">
      <div className="subscribe-name">Outlook</div>
      <div className="subscribe-meta">未连接</div>
      </div>
      <Switch />
      </div>
      <div className="subscribe-item">
      <div className="subscribe-icon">📅</div>
      <div className="subscribe-info">
      <div className="subscribe-name">iCal 订阅</div>
      <div className="subscribe-meta">未连接</div>
      </div>
      <Switch />
      </div>
      </section>
      <section className="card">
      <div className="card-title">日历分类</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">生活</div>
      <div className="setting-desc">私密</div>
      </div>
      <div className="setting-value" style={{ color: "#10B981" }}>● 翠绿</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">工作</div>
      <div className="setting-desc">工作内部</div>
      </div>
      <div className="setting-value" style={{ color: "#E11D48" }}>● 玫红</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">学习</div>
      <div className="setting-desc">私密</div>
      </div>
      <div className="setting-value" style={{ color: "#D946EF" }}>● 粉紫</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">项目里程碑</div>
      <div className="setting-desc">跟随项目</div>
      </div>
      <div className="setting-value" style={{ color: "#F97316" }}>● 橙</div>
      </div>
      </section>
    </>
  )
}

export function SettingsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">日程设置</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">时区</div>
      <div className="setting-desc">用于日历显示</div>
      </div>
      <select className="select">
      <option>Asia/Shanghai (UTC+8)</option>
      <option>UTC</option>
      <option>America/New_York</option>
      </select>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">默认视图</div>
      <div className="setting-desc">打开日程时默认显示</div>
      </div>
      <select className="select">
      <option>月视图</option>
      <option>周视图</option>
      <option>日视图</option>
      <option>议程</option>
      </select>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">默认提醒</div>
      <div className="setting-desc">日程开始前多久提醒</div>
      </div>
      <select className="select">
      <option>15 分钟前</option>
      <option>30 分钟前</option>
      <option>1 小时前</option>
      <option>不提醒</option>
      </select>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">显示周数</div>
      <div className="setting-desc">在月视图显示第几周</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">显示农历</div>
      <div className="setting-desc">在月视图显示农历</div>
      </div>
      <Switch />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">显示已完成日程</div>
      <div className="setting-desc">过去的日程是否显示</div>
      </div>
      <Switch defaultOn />
      </div>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <button className="btn btn-ghost" id="aiAdd" onClick={() => handlers.aiAddOpen()}>✨ AI 找空闲</button>
      <button className="btn btn-primary" id="newEventBtn" onClick={() => handlers.newEventBtnOpen()}>+ 新建日程</button>
    </>
  )
}

/** 弹窗体：原型 `newEventBtn` 标题「新建日程」 */
export function NewEventBtnModal({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <div className="form-field">
      <label className="form-label">标题</label>
      <input className="form-input" placeholder="日程标题..." />
      </div>
      <div className="form-field">
      <label className="form-label">日历</label>
      <select className="form-select">
      <option>生活</option>
      <option>工作</option>
      <option>学习</option>
      <option>项目里程碑</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">日期</label>
      <input className="form-input" type="date" defaultValue="2026-09-20" />
      </div>
      <div className="form-field">
      <label className="form-label">开始时间</label>
      <input className="form-input" type="time" defaultValue="14:00" />
      </div>
      <div className="form-field">
      <label className="form-label">结束时间</label>
      <input className="form-input" type="time" defaultValue="15:00" />
      </div>
      <div className="form-field">
      <label className="form-label">全天</label>
      <select className="form-select">
      <option>否</option>
      <option>是</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">地点</label>
      <input className="form-input" placeholder="会议室 A / 线上" />
      </div>
      <div className="form-field">
      <label className="form-label">提醒</label>
      <select className="form-select">
      <option>15 分钟前</option>
      <option>30 分钟前</option>
      <option>1 小时前</option>
      <option>不提醒</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">备注</label>
      <textarea className="form-textarea" placeholder="补充说明..."></textarea>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>取消</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：已创建'); handlers.closeModal() }}>创建</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `aiAdd` 标题「✨ AI 找空闲」 */
export function AiAddModal({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <div className="form-field">
      <label className="form-label">想安排什么？</label>
      <input className="form-input" placeholder="例如：找 1 小时写文档" />
      </div>
      <div className="form-field">
      <label className="form-label">时间范围</label>
      <select className="form-select">
      <option>本周</option>
      <option>下周</option>
      <option>本月</option>
      </select>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>取消</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：AI 推荐时段'); handlers.closeModal() }}>推荐</button>
      </div>
    </>
  )
}

/** 弹窗体：原型 `openEvent` 标题由触发参数决定 */
export function OpenEventModal({ handlers, title }: { handlers: Handlers; title: string }) {
  return (
    <>
      <div className="form-field">
      <label className="form-label">标题</label>
      <input className="form-input" defaultValue={title} />
      </div>
      <div className="form-field">
      <label className="form-label">时间</label>
      <input className="form-input" defaultValue="2026-09-20 14:00 - 15:00" />
      </div>
      <div className="form-field">
      <label className="form-label">日历</label>
      <select className="form-select">
      <option>工作</option>
      <option>生活</option>
      <option>学习</option>
      </select>
      </div>
      <div className="form-field">
      <label className="form-label">地点</label>
      <input className="form-input" defaultValue="会议室 A" />
      </div>
      <div className="form-field">
      <label className="form-label">备注</label>
      <textarea className="form-textarea">项目评审，准备演示文档。</textarea>
      </div>
      <div className="form-actions">
      <button className="btn btn-ghost" onClick={() => handlers.notice('原型演示：删除')}>删除</button>
      <button className="btn btn-ghost" onClick={() => handlers.closeModal()}>关闭</button>
      <button className="btn btn-primary" onClick={() => { handlers.notice('原型演示：已保存'); handlers.closeModal() }}>保存</button>
      </div>
    </>
  )
}
