/* @generated by design/gen-workspace-pages.mjs —— 请勿手改 */
/**
 * settings 模块的面板与弹窗标记。
 *
 * 事实源：design/setting/setting_index.html
 * 重新生成：node design/gen-workspace-pages.mjs
 *
 * 这里**只有标记**，没有行为：每个 onclick 都被翻译成 `handlers.xxx(...)`，
 * 实现写在手写的 <SettingsWorkspace />（同目录）。
 */

import { Switch, ThemeSwatches } from '../../../components/workspace/toggles'

import type { ModuleTab } from '../../../data/workspace/types'

/** Tab 定义（键 + 标签）。标签与原型顶栏面包屑的 titleMap 交叉校验过。 */
export const TABS: ModuleTab[] = [
  { key: 'account', label: '账户与安全' },
  { key: 'modules', label: '模块管理' },
  { key: 'appearance', label: '主题与外观' },
  { key: 'notifications', label: '通知提醒' },
  { key: 'data', label: '数据与备份' },
  { key: 'integrations', label: '集成与 API' },
  { key: 'ai', label: 'AI 设置' },
  { key: 'privacy', label: '权限与隐私' },
  { key: 'shortcuts', label: '快捷键' },
  { key: 'about', label: '关于' },
]

/** 本模块所有交互回调 —— 实现写在 <SettingsWorkspace /> 里。 */
export interface Handlers {
  notice: (arg0: string) => void
}

export const MODAL_SPECS = {
} as const

export type ModalKey = keyof typeof MODAL_SPECS

export function AccountPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">账户信息</div>
      <div className="setting-row">
      <div className="avatar-lg">杨</div>
      <div className="setting-info">
      <div className="setting-label">杨刘</div>
      <div className="setting-desc">yangliu@example.com</div>
      </div>
      <button className="btn btn-ghost">编辑</button>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">昵称</div>
      <div className="setting-desc">显示在系统内</div>
      </div>
      <div className="setting-value">杨刘</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">邮箱</div>
      <div className="setting-desc">用于登录和通知</div>
      </div>
      <div className="setting-value">yangliu@example.com</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">安全</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">密码</div>
      <div className="setting-desc">上次修改：30 天前</div>
      </div>
      <button className="btn btn-ghost">修改</button>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">两步验证</div>
      <div className="setting-desc">登录时需要额外验证</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">登录设备</div>
      <div className="setting-desc">当前有 2 台设备登录</div>
      </div>
      <button className="btn btn-ghost">管理</button>
      </div>
      </section>
    </>
  )
}

export function ModulesPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">模块开关</div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#6366F1" }}></div>
      <div className="module-name">工作台</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#F59E0B" }}></div>
      <div className="module-name">任务清单</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#0EA5E9" }}></div>
      <div className="module-name">日程</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#10B981" }}></div>
      <div className="module-name">生活</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#E11D48" }}></div>
      <div className="module-name">工作</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#D946EF" }}></div>
      <div className="module-name">学习</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#F97316" }}></div>
      <div className="module-name">项目</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="module-item">
      <div className="module-info">
      <div className="module-dot" style={{ background: "#14B8A6" }}></div>
      <div className="module-name">知识库</div>
      </div>
      <Switch defaultOn />
      </div>
      </section>
    </>
  )
}

export function AppearancePanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">主题</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">颜色模式</div>
      <div className="setting-desc">亮色 / 暗色 / 跟随系统</div>
      </div>
      <ThemeSwatches />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">弥散背景</div>
      <div className="setting-desc">低饱和色团 + 毛玻璃</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">动画效果</div>
      <div className="setting-desc">色团漂移、悬停动效</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">紧凑模式</div>
      <div className="setting-desc">减少间距，显示更多内容</div>
      </div>
      <Switch />
      </div>
      </section>
      <section className="card">
      <div className="card-title">模块主题色</div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">工作台</div></div>
      <div className="setting-value" style={{ color: "#6366F1" }}>靛蓝 #6366F1</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">任务清单</div></div>
      <div className="setting-value" style={{ color: "#F59E0B" }}>琥珀 #F59E0B</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">日程</div></div>
      <div className="setting-value" style={{ color: "#0EA5E9" }}>天蓝 #0EA5E9</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">生活</div></div>
      <div className="setting-value" style={{ color: "#10B981" }}>翠绿 #10B981</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">工作</div></div>
      <div className="setting-value" style={{ color: "#E11D48" }}>玫红 #E11D48</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">学习</div></div>
      <div className="setting-value" style={{ color: "#D946EF" }}>粉紫 #D946EF</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">项目</div></div>
      <div className="setting-value" style={{ color: "#F97316" }}>橙 #F97316</div>
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">知识库</div></div>
      <div className="setting-value" style={{ color: "#14B8A6" }}>青色 #14B8A6</div>
      </div>
      </section>
    </>
  )
}

export function NotificationsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">通知</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">任务提醒</div>
      <div className="setting-desc">任务到期前提醒</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">日程提醒</div>
      <div className="setting-desc">日程开始前 15 分钟</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">习惯打卡提醒</div>
      <div className="setting-desc">每天固定时间提醒</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">复习提醒</div>
      <div className="setting-desc">有卡片到期时提醒</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">里程碑提醒</div>
      <div className="setting-desc">项目里程碑临近时提醒</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">宠物提醒</div>
      <div className="setting-desc">疫苗、驱虫到期提醒</div>
      </div>
      <Switch defaultOn />
      </div>
      </section>
      <section className="card">
      <div className="card-title">提醒方式</div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">站内通知</div></div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">邮件通知</div></div>
      <Switch />
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">浏览器推送</div></div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info"><div className="setting-label">手机推送</div></div>
      <Switch />
      </div>
      </section>
    </>
  )
}

export function DataPanel({ handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">数据</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">本地存储</div>
      <div className="setting-desc">使用 IndexedDB / SQLite</div>
      </div>
      <div className="setting-value">128 MB</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">云同步</div>
      <div className="setting-desc">同步到私有服务器</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">上次备份</div>
      <div className="setting-desc">自动备份，每天一次</div>
      </div>
      <div className="setting-value">今天 03:00</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">导入导出</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">导出全部数据</div>
      <div className="setting-desc">JSON / Markdown / CSV</div>
      </div>
      <button className="btn btn-ghost" onClick={() => handlers.notice('原型演示：导出数据')}>导出</button>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">从 Obsidian 导入</div>
      <div className="setting-desc">导入 Markdown 笔记</div>
      </div>
      <button className="btn btn-ghost" onClick={() => handlers.notice('原型演示：导入')}>导入</button>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">从 Notion 导入</div>
      <div className="setting-desc">导入页面和数据库</div>
      </div>
      <button className="btn btn-ghost" onClick={() => handlers.notice('原型演示：导入')}>导入</button>
      </div>
      </section>
      <section className="card danger-zone">
      <div className="card-title" style={{ color: "#EF4444" }}>危险操作</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">清空所有数据</div>
      <div className="setting-desc">不可恢复，请先备份</div>
      </div>
      <button className="btn btn-danger" onClick={() => handlers.notice('原型演示：请谨慎操作')}>清空</button>
      </div>
      </section>
    </>
  )
}

export function IntegrationsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">集成</div>
      <div className="integration-item">
      <div className="integration-icon">🐙</div>
      <div className="integration-info">
      <div className="integration-name">GitHub</div>
      <div className="integration-meta">关联仓库、提交记录</div>
      </div>
      <button className="btn btn-ghost">连接</button>
      </div>
      <div className="integration-item">
      <div className="integration-icon">📅</div>
      <div className="integration-info">
      <div className="integration-name">Google Calendar</div>
      <div className="integration-meta">同步日程</div>
      </div>
      <button className="btn btn-ghost">连接</button>
      </div>
      <div className="integration-item">
      <div className="integration-icon">📝</div>
      <div className="integration-info">
      <div className="integration-name">Notion</div>
      <div className="integration-meta">导入笔记、数据库</div>
      </div>
      <button className="btn btn-ghost">连接</button>
      </div>
      <div className="integration-item">
      <div className="integration-icon">💬</div>
      <div className="integration-info">
      <div className="integration-name">企业微信 / 飞书</div>
      <div className="integration-meta">消息通知</div>
      </div>
      <button className="btn btn-ghost">连接</button>
      </div>
      </section>
      <section className="card">
      <div className="card-title">API</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">API Token</div>
      <div className="setting-desc">用于外部调用</div>
      </div>
      <button className="btn btn-ghost">生成</button>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">Webhook</div>
      <div className="setting-desc">事件推送到指定 URL</div>
      </div>
      <button className="btn btn-ghost">配置</button>
      </div>
      </section>
    </>
  )
}

export function AiPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">AI 能力</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">启用 AI 助手</div>
      <div className="setting-desc">命令面板 Cmd + K、页面内嵌</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">模型</div>
      <div className="setting-desc">选择默认模型</div>
      </div>
      <select className="select">
      <option>Claude</option>
      <option>GPT</option>
      <option>本地模型</option>
      </select>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">API Key</div>
      <div className="setting-desc">不存明文，只存引用</div>
      </div>
      <button className="btn btn-ghost">配置</button>
      </div>
      </section>
      <section className="card">
      <div className="card-title">隐私</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">工作数据不进 AI</div>
      <div className="setting-desc">工作机密默认不进入上下文</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">本次对话不记录</div>
      <div className="setting-desc">临时会话不写日志</div>
      </div>
      <Switch />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">AI 调用日志</div>
      <div className="setting-desc">记录调用，便于审计</div>
      </div>
      <Switch defaultOn />
      </div>
      </section>
    </>
  )
}

export function PrivacyPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">权限</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">生活数据</div>
      <div className="setting-desc">private / family</div>
      </div>
      <div className="setting-value">私有</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">工作数据</div>
      <div className="setting-desc">work-internal / confidential</div>
      </div>
      <div className="setting-value">工作内部</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">学习数据</div>
      <div className="setting-desc">private / public</div>
      </div>
      <div className="setting-value">私有</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">隐私</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">敏感信息脱敏</div>
      <div className="setting-desc">自动识别并脱敏</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">审计日志</div>
      <div className="setting-desc">记录关键操作</div>
      </div>
      <Switch defaultOn />
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">工作机密本地加密</div>
      <div className="setting-desc">本地文件加密存储</div>
      </div>
      <Switch defaultOn />
      </div>
      </section>
    </>
  )
}

export function ShortcutsPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">全局快捷键</div>
      <div className="shortcut-row">
      <span>打开命令面板</span>
      <span><span className="kbd">⌘</span> <span className="kbd">K</span></span>
      </div>
      <div className="shortcut-row">
      <span>快速新建</span>
      <span><span className="kbd">⌘</span> <span className="kbd">N</span></span>
      </div>
      <div className="shortcut-row">
      <span>全局搜索</span>
      <span><span className="kbd">⌘</span> <span className="kbd">/</span></span>
      </div>
      <div className="shortcut-row">
      <span>切换主题</span>
      <span><span className="kbd">⌘</span> <span className="kbd">⇧</span> <span className="kbd">L</span></span>
      </div>
      </section>
      <section className="card">
      <div className="card-title">模块快捷键</div>
      <div className="shortcut-row">
      <span>切换模块</span>
      <span><span className="kbd">⌘</span> <span className="kbd">1</span> ~ <span className="kbd">9</span></span>
      </div>
      <div className="shortcut-row">
      <span>新建任务</span>
      <span><span className="kbd">T</span></span>
      </div>
      <div className="shortcut-row">
      <span>新建笔记</span>
      <span><span className="kbd">N</span></span>
      </div>
      <div className="shortcut-row">
      <span>新建日程</span>
      <span><span className="kbd">E</span></span>
      </div>
      </section>
    </>
  )
}

export function AboutPanel({ handlers: _handlers }: { handlers: Handlers }) {
  return (
    <>
      <section className="card">
      <div className="card-title">关于</div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">个人系统</div>
      <div className="setting-desc">生活 / 工作 / 学习 / 项目 / 知识库 / 设置</div>
      </div>
      <div className="setting-value">v1.0.0</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">技术栈</div>
      <div className="setting-desc">Vite + React 19 + TypeScript</div>
      </div>
      <div className="setting-value">-</div>
      </div>
      <div className="setting-row">
      <div className="setting-info">
      <div className="setting-label">最近更新</div>
      <div className="setting-desc">2026-09-20</div>
      </div>
      <div className="setting-value">-</div>
      </div>
      </section>
      <section className="card">
      <div className="card-title">更新日志</div>
      <div className="notice">
      v1.0.0 · 2026-09-20<br />
      初始版本，包含 9 模块、弥散风格、亮暗双模式。
      </div>
      </section>
    </>
  )
}

/**
 * 顶栏动作区 —— 原型的 `.topbar-actions` 里的按钮。
 *
 * 为什么要生成：这排按钮**每个模块都不一样**（任务页是「AI 拆解 / 新建任务」，
 * 生活页是「快速记录」，设置页一个都没有）。只把它们交给外壳会全丢掉 ——
 * 而且丢得没有声响：外壳照常渲染，只是那排主入口不存在了。
 * 主题开关已从这里剔掉（外壳自己提供一份，全站只能有一个主题开关）。
 */
export function TopbarActions({ handlers: _handlers }: { handlers: Handlers }) {
  return null
}
